




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace Ssz.Operator.Core.Properties
{ 
    public class ResourceStrings
    {
        
public const String GeometryInfoSupplierLLineXaml = @"GeometryInfoSupplierLLineXaml";
        
public const String ClassicButtonStyleXaml = @"ClassicButtonStyleXaml";
        
public const String TrivialButtonStyleXaml = @"TrivialButtonStyleXaml";
        
public const String InvisibleButtonStyleXaml = @"InvisibleButtonStyleXaml";
        
public const String ClassicSliderStyleXaml = @"ClassicSliderStyleXaml";
        
public const String ContentSliderStyleXaml = @"ContentSliderStyleXaml";
        
public const String TouchScreenSliderStyleXaml = @"TouchScreenSliderStyleXaml";
        
public const String GeometryInfoSupplierHorizontalLineXaml = @"GeometryInfoSupplierHorizontalLineXaml";
        
public const String GeometryInfoSupplierVerticalLineXaml = @"GeometryInfoSupplierVerticalLineXaml";
        
public const String DefaultButtonStyleXaml = @"DefaultButtonStyleXaml";
        
public const String ClassicToggleButtonStyleXaml = @"ClassicToggleButtonStyleXaml";
        
public const String DefaultToggleButtonStyleXaml = @"DefaultToggleButtonStyleXaml";
        
public const String InvisibleToggleButtonStyleXaml = @"InvisibleToggleButtonStyleXaml";
        
public const String TrivialToggleButtonStyleXaml = @"TrivialToggleButtonStyleXaml";
        
public const String GeometryInfoSupplierEllipseXaml = @"GeometryInfoSupplierEllipseXaml";
        
public const String GeometryInfoSupplierRectangleXaml = @"GeometryInfoSupplierRectangleXaml";
        
public const String ClassicComboBoxStyleXaml = @"ClassicComboBoxStyleXaml";
        
public const String DefaultComboBoxStyleXaml = @"DefaultComboBoxStyleXaml";
        
public const String GeometryInfoSupplierLLineRoundCornerXaml = @"GeometryInfoSupplierLLineRoundCornerXaml";
        
public const String DefaultGeometryButtonStyleXaml = @"DefaultGeometryButtonStyleXaml";
        
public const String GeometryInfoSupplierRectangleRoundCornersXaml = @"GeometryInfoSupplierRectangleRoundCornersXaml";
        
public const String MultiChartDsShapeGeometryInfoSupplierCircleXaml = @"MultiChartDsShapeGeometryInfoSupplierCircleXaml";
        
public const String MultiChartDsShapeGeometryInfoSupplierCrossXaml = @"MultiChartDsShapeGeometryInfoSupplierCrossXaml";
        
public const String AddDrawingsFromLibraryDialogTitle = @"AddDrawingsFromLibraryDialogTitle";
        
public const String AddonBaseSszOperatorVersion = @"AddonBaseSszOperatorVersion";
        
public const String AddonBaseDescription = @"AddonBaseDescription";
        
public const String AddonBaseNameToDisplay = @"AddonBaseNameToDisplay";
        
public const String AddonBaseDllFileFullName = @"AddonBaseDllFileFullName";
        
public const String AddonBaseVersion = @"AddonBaseVersion";
        
public const String AddonSszDsProjectPlay = @"AddonSszDsProjectPlay";
        
public const String AddonDeserializationError = @"AddonDeserializationError";
        
public const String AddonDeserializationErrorUnsupportedFileVersion = @"AddonDeserializationErrorUnsupportedFileVersion";
        
public const String AddonDeserializationErrorUnsupportedVersion = @"AddonDeserializationErrorUnsupportedVersion";
        
public const String AddonNotFoundMessage = @"AddonNotFoundMessage";
        
public const String AddonPropertiesCellText = @"AddonPropertiesCellText";
        
public const String AddonsCategory = @"AddonsCategory";
        
public const String AddonSerializationError = @"AddonSerializationError";
        
public const String AddonUnavailable = @"AddonUnavailable";
        
public const String AddonUnavailableMessage = @"AddonUnavailableMessage";
        
public const String AddRemoveAddonsButtonText = @"AddRemoveAddonsButtonText";
        
public const String AdvancedCategory = @"AdvancedCategory";
        
public const String AlarmListDsShapeAppearanceType = @"AlarmListDsShapeAppearanceType";
        
public const String AllDsPageDrawingsComboBoxItem = @"AllDsPageDrawingsComboBoxItem";
        
public const String AllDsShapeDrawingsComboBoxItem = @"AllDsShapeDrawingsComboBoxItem";
        
public const String AllOpenedDrawingsComboBoxItem = @"AllOpenedDrawingsComboBoxItem";
        
public const String AllPropertiesComboBoxItem = @"AllPropertiesComboBoxItem";
        
public const String AppearanceCategory = @"AppearanceCategory";
        
public const String AppInfoCategory = @"AppInfoCategory";
        
public const String ApplyToOtherDsShapesQuestion = @"ApplyToOtherDsShapesQuestion";
        
public const String BackupDrawingWasCreated = @"BackupDrawingWasCreated";
        
public const String BasicCategory = @"BasicCategory";
        
public const String BehaviourCategory = @"BehaviourCategory";
        
public const String BlinkingBrushTabItem = @"BlinkingBrushTabItem";
        
public const String BrowseButtonLabel = @"BrowseButtonLabel";
        
public const String BrowserDsShapeUrl = @"BrowserDsShapeUrl";
        
public const String BrushConverterWindowIfExpression = @"BrushConverterWindowIfExpression";
        
public const String ButtonDsShapeBase_ClickDsCommand = @"ButtonDsShapeBase_ClickDsCommand";
        
public const String ButtonDsShapeBase_DoubleClickDsCommand = @"ButtonDsShapeBase_DoubleClickDsCommand";
        
public const String ButtonDsShapeBase_HoldCommandDelayMs = @"ButtonDsShapeBase_HoldCommandDelayMs";
        
public const String ButtonDsShapeBase_HoldCommandDelayMsDescription = @"ButtonDsShapeBase_HoldCommandDelayMsDescription";
        
public const String ButtonDsShapeBase_HoldCommandIntervalMs = @"ButtonDsShapeBase_HoldCommandIntervalMs";
        
public const String ButtonDsShapeBase_HoldCommandIntervalMsDescription = @"ButtonDsShapeBase_HoldCommandIntervalMsDescription";
        
public const String ButtonDsShapeBase_HoldDsCommand = @"ButtonDsShapeBase_HoldDsCommand";
        
public const String ButtonDsShapeBase_IsCancelInfo = @"ButtonDsShapeBase_IsCancelInfo";
        
public const String ButtonDsShapeBase_IsCancelInfoDescription = @"ButtonDsShapeBase_IsCancelInfoDescription";
        
public const String ButtonDsShapeBase_IsDefaultInfo = @"ButtonDsShapeBase_IsDefaultInfo";
        
public const String ButtonDsShapeBase_IsDefaultInfoDescription = @"ButtonDsShapeBase_IsDefaultInfoDescription";
        
public const String ButtonDsShape_ContentHorizontalAlignment = @"ButtonDsShape_ContentHorizontalAlignment";
        
public const String ButtonDsShape_ContentInfo = @"ButtonDsShape_ContentInfo";
        
public const String ButtonDsShape_ContentVerticalAlignment = @"ButtonDsShape_ContentVerticalAlignment";
        
public const String ButtonDsShape_PressedContentInfo = @"ButtonDsShape_PressedContentInfo";
        
public const String ButtonDsShape_TextHorizontalAlignment = @"ButtonDsShape_TextHorizontalAlignment";
        
public const String ButtonDsShape_TextInfo = @"ButtonDsShape_TextInfo";
        
public const String ButtonDsShape_TextMargin = @"ButtonDsShape_TextMargin";
        
public const String ButtonDsShape_TextStretch = @"ButtonDsShape_TextStretch";
        
public const String ButtonDsShape_TextVerticalAlignment = @"ButtonDsShape_TextVerticalAlignment";
        
public const String ButtonDsShape_TextWrapping = @"ButtonDsShape_TextWrapping";
        
public const String CancelButtonText = @"CancelButtonText";
        
public const String CannotCreateDsShapeView = @"CannotCreateDsShapeView";
        
public const String CannotFindFaceplateForTag = @"CannotFindFaceplateForTag";
        
public const String CannotSaveFileMessage = @"CannotSaveFileMessage";
        
public const String CannotShowDsPage = @"CannotShowDsPage";
        
public const String CentumTrendGroupDsShapeDsTrendItemsCollection = @"CentumTrendGroupDsShapeDsTrendItemsCollection";
        
public const String ChangeControlStyleQuestion = @"ChangeControlStyleQuestion";
        
public const String ChangedDsPagesCount = @"ChangedDsPagesCount";
        
public const String ChartDsShapeAppearanceType = @"ChartDsShapeAppearanceType";
        
public const String ChartDsShapeDsChartItemsCollection = @"ChartDsShapeDsChartItemsCollection";
        
public const String CheckDrawingsBinSerializationVersion = @"CheckDrawingsBinSerializationVersion";
        
public const String ChildWindowInfo = @"ChildWindowInfo";
        
public const String ChildWindowInfoDescription = @"ChildWindowInfoDescription";
        
public const String ClearAllButtonText = @"ClearAllButtonText";
        
public const String ClickCoordinate = @"ClickCoordinate";
        
public const String CloneableObjectProperties = @"CloneableObjectProperties";
        
public const String CloseAllFaceplatesDsCommandOptions_PlayWindowClassInfo = @"CloseAllFaceplatesDsCommandOptions_PlayWindowClassInfo";
        
public const String CloseAllFaceplatesDsCommandOptions_PlayWindowClassInfo_Description = @"CloseAllFaceplatesDsCommandOptions_PlayWindowClassInfo_Description";
        
public const String CloseButtonToolTip = @"CloseButtonToolTip";
        
public const String CloseDsProjectToolkitOperation = @"CloseDsProjectToolkitOperation";
        
public const String ColorFromConstant = @"ColorFromConstant";
        
public const String ColorFromConstantToolTip = @"ColorFromConstantToolTip";
        
public const String ColorFromScreen = @"ColorFromScreen";
        
public const String ColorFromScreenToolTip = @"ColorFromScreenToolTip";
        
public const String ComboBoxDsShapeIsEditableInfo = @"ComboBoxDsShapeIsEditableInfo";
        
public const String ComboBoxDsShapeMenuItemInfosCollection = @"ComboBoxDsShapeMenuItemInfosCollection";
        
public const String ComboBoxDsShapeSelectedIndexInfo = @"ComboBoxDsShapeSelectedIndexInfo";
        
public const String ComboBoxDsShapeTextInfo = @"ComboBoxDsShapeTextInfo";
        
public const String CommandListenerDsShape_CommandToListen = @"CommandListenerDsShape_CommandToListen";
        
public const String CommandListenerDsShape_CommandToListenDescription = @"CommandListenerDsShape_CommandToListenDescription";
        
public const String CommandListenerDsShape_CommandToListenDsCommand = @"CommandListenerDsShape_CommandToListenDsCommand";
        
public const String CommandListenerDsShape_CommandToListenDsCommandDescription = @"CommandListenerDsShape_CommandToListenDsCommandDescription";
        
public const String CommandListenerDsShape_CommandToListenOptions = @"CommandListenerDsShape_CommandToListenOptions";
        
public const String CommandListenerDsShape_CommandToListenOptionsDescription = @"CommandListenerDsShape_CommandToListenOptionsDescription";
        
public const String CommandListenerDsShape_ConditionalDsCommandsCollection = @"CommandListenerDsShape_ConditionalDsCommandsCollection";
        
public const String CommandListenerDsShape_ConditionalDsCommandsCollectionDescription = @"CommandListenerDsShape_ConditionalDsCommandsCollectionDescription";
        
public const String CommandListenerDsShape_EachSecondDsCommand = @"CommandListenerDsShape_EachSecondDsCommand";
        
public const String CommandListenerDsShape_EachSecondDsCommandDescription = @"CommandListenerDsShape_EachSecondDsCommandDescription";
        
public const String CommandListenerDsShape_LoadedDsCommand = @"CommandListenerDsShape_LoadedDsCommand";
        
public const String CommandListenerDsShape_LoadedDsCommandDescription = @"CommandListenerDsShape_LoadedDsCommandDescription";
        
public const String CommandListenerDsShape_UnloadedDsCommand = @"CommandListenerDsShape_UnloadedDsCommand";
        
public const String CommandListenerDsShape_UnloadedDsCommandDescription = @"CommandListenerDsShape_UnloadedDsCommandDescription";
        
public const String CommandsListDsCommandOptionsDsCommandsList = @"CommandsListDsCommandOptionsDsCommandsList";
        
public const String ComplexDsShape = @"ComplexDsShape";
        
public const String ComplexDsShapeDesc = @"ComplexDsShapeDesc";
        
public const String ComplexDsShapeDsConstantsCollection = @"ComplexDsShapeDsConstantsCollection";
        
public const String ComplexDsShapeGroup = @"ComplexDsShapeGroup";
        
public const String ComplexDsShapeName = @"ComplexDsShapeName";
        
public const String ComplexDsShape_DrawingCenterRelativePosition = @"ComplexDsShape_DrawingCenterRelativePosition";
        
public const String ComplexDsShape_DrawingDesc = @"ComplexDsShape_DrawingDesc";
        
public const String ComplexDsShape_DrawingGroup = @"ComplexDsShape_DrawingGroup";
        
public const String ComplexDsShape_DrawingGuid = @"ComplexDsShape_DrawingGuid";
        
public const String ComplexDsShape_DrawingHeight = @"ComplexDsShape_DrawingHeight";
        
public const String ComplexDsShape_DrawingName = @"ComplexDsShape_DrawingName";
        
public const String ComplexDsShape_DrawingWidth = @"ComplexDsShape_DrawingWidth";
        
public const String ConnectionPointDsShape_Type = @"ConnectionPointDsShape_Type";
        
public const String ConnectorDsShape_Begin = @"ConnectorDsShape_Begin";
        
public const String ConnectorDsShape_End = @"ConnectorDsShape_End";
        
public const String ConnectorDsShape_Type = @"ConnectorDsShape_Type";
        
public const String ConstantsValuesOnlyComboBoxItem = @"ConstantsValuesOnlyComboBoxItem";
        
public const String ConstantValueIsInherited = @"ConstantValueIsInherited";
        
public const String ConstantValueNotInListWarning = @"ConstantValueNotInListWarning";
        
public const String ContentButtonDsShape_HorizontalTextAlignment = @"ContentButtonDsShape_HorizontalTextAlignment";
        
public const String ContentButtonDsShape_TextMargin = @"ContentButtonDsShape_TextMargin";
        
public const String ContentButtonDsShape_TextStretch = @"ContentButtonDsShape_TextStretch";
        
public const String ContentButtonDsShape_VerticalTextAlignment = @"ContentButtonDsShape_VerticalTextAlignment";
        
public const String ContentDsShapeContentInfo = @"ContentDsShapeContentInfo";
        
public const String ContentEditorClearContentButtonText = @"ContentEditorClearContentButtonText";
        
public const String ContentEditorContentStretch = @"ContentEditorContentStretch";
        
public const String ContentEditorCurrentContentDesc = @"ContentEditorCurrentContentDesc";
        
public const String ContentEditorSelectFileButtonText = @"ContentEditorSelectFileButtonText";
        
public const String ContentEditorSelectFileFromLibraryButtonText = @"ContentEditorSelectFileFromLibraryButtonText";
        
public const String ContentEditorSelectStretch = @"ContentEditorSelectStretch";
        
public const String ContentEditorWindowBlinkingFirstTabText = @"ContentEditorWindowBlinkingFirstTabText";
        
public const String ContentEditorWindowBlinkingSecondTabText = @"ContentEditorWindowBlinkingSecondTabText";
        
public const String ContentEditorWindowBlinkingTabText = @"ContentEditorWindowBlinkingTabText";
        
public const String ContentEditorWindowStaticTabText = @"ContentEditorWindowStaticTabText";
        
public const String ContextMenuDsShapeMenuItemInfosCollection = @"ContextMenuDsShapeMenuItemInfosCollection";
        
public const String ControlDsShapeBackgroundInfo = @"ControlDsShapeBackgroundInfo";
        
public const String ControlDsShapeBorderBrushInfo = @"ControlDsShapeBorderBrushInfo";
        
public const String ControlDsShapeBorderThickness = @"ControlDsShapeBorderThickness";
        
public const String ControlDsShapeForegroundInfo = @"ControlDsShapeForegroundInfo";
        
public const String ControlDsShapeHorizontalContentAlignment = @"ControlDsShapeHorizontalContentAlignment";
        
public const String ControlDsShapePadding = @"ControlDsShapePadding";
        
public const String ControlDsShapeStyleInfo = @"ControlDsShapeStyleInfo";
        
public const String ControlDsShapeToolTipFileRelativePath = @"ControlDsShapeToolTipFileRelativePath";
        
public const String ControlDsShapeToolTipTextInfo = @"ControlDsShapeToolTipTextInfo";
        
public const String ControlDsShapeVerticalContentAlignment = @"ControlDsShapeVerticalContentAlignment";
        
public const String ConvertAllDrawingsToNewDrawingsStoreModeQuestion = @"ConvertAllDrawingsToNewDrawingsStoreModeQuestion";
        
public const String Converter = @"Converter";
        
public const String ConverterClear = @"ConverterClear";
        
public const String ConverterHelp = @"ConverterHelp";
        
public const String ConverterLoad = @"ConverterLoad";
        
public const String ConverterMoveDown = @"ConverterMoveDown";
        
public const String ConverterMoveUp = @"ConverterMoveUp";
        
public const String ConverterSave = @"ConverterSave";
        
public const String ConverterWindowDataSourceToUi = @"ConverterWindowDataSourceToUi";
        
public const String ConverterWindowDataSourceToUiValueExpression = @"ConverterWindowDataSourceToUiValueExpression";
        
public const String ConverterWindowHelp = @"ConverterWindowHelp";
        
public const String ConverterWindowHelp2 = @"ConverterWindowHelp2";
        
public const String ConverterWindowUiToDataSource = @"ConverterWindowUiToDataSource";
        
public const String ConverterWindowUiToDataSourceIfExpression = @"ConverterWindowUiToDataSourceIfExpression";
        
public const String ConverterWindowUiToDataSourceParamNum = @"ConverterWindowUiToDataSourceParamNum";
        
public const String ConverterWindowUiToDataSourceValueExpression = @"ConverterWindowUiToDataSourceValueExpression";
        
public const String Copy = @"Copy";
        
public const String CopyResultsButton = @"CopyResultsButton";
        
public const String CreateDsPagesToolkitOperationOptions_TemplateDsPageDrawingFileName = @"CreateDsPagesToolkitOperationOptions_TemplateDsPageDrawingFileName";
        
public const String CreateDsPagesToolkitOperationOptions_TemplateDsPageDrawingFileName_Description = @"CreateDsPagesToolkitOperationOptions_TemplateDsPageDrawingFileName_Description";
        
public const String CreateDsPagesToolkitOperationOptions_TryCreateDsPagesWithSizeOfImage = @"CreateDsPagesToolkitOperationOptions_TryCreateDsPagesWithSizeOfImage";
        
public const String CreateDsPagesToolkitOperationOptions_TryCreateDsPagesWithSizeOfImage_Description = @"CreateDsPagesToolkitOperationOptions_TryCreateDsPagesWithSizeOfImage_Description";
        
public const String CreateMapToolkitOperationOptionsMaxPointsDelta = @"CreateMapToolkitOperationOptionsMaxPointsDelta";
        
public const String CreateMapToolkitOperationOptionsMutualPointRefsMaxAngleDelta = @"CreateMapToolkitOperationOptionsMutualPointRefsMaxAngleDelta";
        
public const String CurrentDrawingComboBoxItem = @"CurrentDrawingComboBoxItem";
        
public const String CustomControlStyle = @"CustomControlStyle";
        
public const String Cut = @"Cut";
        
public const String DataCategory = @"DataCategory";
        
public const String DataEngineBaseDescription = @"DataEngineBaseDescription";
        
public const String DataEngineBase_AlarmMessages_ElementIdsMapFileName = @"DataEngineBase_AlarmMessages_ElementIdsMapFileName";
        
public const String DataEngineBase_AlarmMessages_ElementIdsMapFileNameDescription = @"DataEngineBase_AlarmMessages_ElementIdsMapFileNameDescription";
        
public const String DataEngineBase_Constant = @"DataEngineBase_Constant";
        
public const String DataEngineBase_ElementIdsMapFileName = @"DataEngineBase_ElementIdsMapFileName";
        
public const String DataEngineBase_ElementIdsMapFileName_Description = @"DataEngineBase_ElementIdsMapFileName_Description";
        
public const String DataEngineBase_FontsMapFileName = @"DataEngineBase_FontsMapFileName";
        
public const String DataEngineBase_FontsMapFileName_Description = @"DataEngineBase_FontsMapFileName_Description";
        
public const String DataEngineBase_GlobalVariablesFileName = @"DataEngineBase_GlobalVariablesFileName";
        
public const String DataEngineBase_GlobalVariablesFileName_Description = @"DataEngineBase_GlobalVariablesFileName_Description";
        
public const String DataEngineBase_ModelTagPropertyInfosCollection = @"DataEngineBase_ModelTagPropertyInfosCollection";
        
public const String DataEngineBase_SymbolsToRemoveFromTagInAlarmMessage = @"DataEngineBase_SymbolsToRemoveFromTagInAlarmMessage";
        
public const String DataEngineBase_SymbolsToRemoveFromTagInAlarmMessage_Description = @"DataEngineBase_SymbolsToRemoveFromTagInAlarmMessage_Description";
        
public const String DataEngineBase_TagAndPropertySeparator = @"DataEngineBase_TagAndPropertySeparator";
        
public const String DataEngineBase_TagAndPropertySeparator_Description = @"DataEngineBase_TagAndPropertySeparator_Description";
        
public const String DataEngineBase_TagDescriptionInfo = @"DataEngineBase_TagDescriptionInfo";
        
public const String DataEngineBase_TagAlarmsInfosCollection = @"DataEngineBase_TagAlarmsInfosCollection";
        
public const String DataEngineBase_TagsFileName = @"DataEngineBase_TagsFileName";
        
public const String DataEngineBase_TagsFileName_Description = @"DataEngineBase_TagsFileName_Description";
        
public const String DataEngineBase_TagNameToDisplayInfo = @"DataEngineBase_TagNameToDisplayInfo";
        
public const String DataEngineBase_TagTypeSeparator = @"DataEngineBase_TagTypeSeparator";
        
public const String DataEngineBase_TagTypeSeparator_Description = @"DataEngineBase_TagTypeSeparator_Description";
        
public const String DataEngineBase_TagTypesFileName = @"DataEngineBase_TagTypesFileName";
        
public const String DataEngineBase_TagTypesFileName_Description = @"DataEngineBase_TagTypesFileName_Description";
        
public const String DataEngineUnavailableDefaultWillBeUsedMessage = @"DataEngineUnavailableDefaultWillBeUsedMessage";
        
public const String DataEngineUnavailableMessage = @"DataEngineUnavailableMessage";
        
public const String DataItemDefaultValue = @"DataItemDefaultValue";
        
public const String DataItemId = @"DataItemId";
        
public const String DataItemType = @"DataItemType";
        
public const String DefaultBrushTabItem = @"DefaultBrushTabItem";
        
public const String DefaultTrendValuesZoomValue = @"DefaultTrendValuesZoomValue";
        
public const String DefaultValue = @"DefaultValue";
        
public const String Delete = @"Delete";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionChangeOfState = @"SszAlarmsInfoCategoryIdNormalizedConditionChangeOfState";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionH = @"SszAlarmsInfoCategoryIdNormalizedConditionH";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionHH = @"SszAlarmsInfoCategoryIdNormalizedConditionHH";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionL = @"SszAlarmsInfoCategoryIdNormalizedConditionL";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionLL = @"SszAlarmsInfoCategoryIdNormalizedConditionLL";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionNormal = @"SszAlarmsInfoCategoryIdNormalizedConditionNormal";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionNotNormalState = @"SszAlarmsInfoCategoryIdNormalizedConditionNotNormalState";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionOther = @"SszAlarmsInfoCategoryIdNormalizedConditionOther";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionSwOff = @"SszAlarmsInfoCategoryIdNormalizedConditionSwOff";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionSwOn = @"SszAlarmsInfoCategoryIdNormalizedConditionSwOn";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionSwTurnOff = @"SszAlarmsInfoCategoryIdNormalizedConditionSwTurnOff";
        
public const String SszAlarmsInfoCategoryIdNormalizedConditionSwTurnOn = @"SszAlarmsInfoCategoryIdNormalizedConditionSwTurnOn";
        
public const String SszDataEngineDescription = @"SszDataEngineDescription";
        
public const String SszDataEngineNameToDisplay = @"SszDataEngineNameToDisplay";
        
public const String DesignModeInPlayFailed = @"DesignModeInPlayFailed";
        
public const String Done = @"Done";
        
public const String DoneWithErrors = @"DoneWithErrors";
        
public const String DrawingCategory = @"DrawingCategory";
        
public const String DrawingDsConstantsCollection = @"DrawingDsConstantsCollection";
        
public const String DrawingFileNotFoundMessage = @"DrawingFileNotFoundMessage";
        
public const String DrawingFileOpenErrorAddonIsNotFound = @"DrawingFileOpenErrorAddonIsNotFound";
        
public const String DrawingFileOpenErrorGeneral = @"DrawingFileOpenErrorGeneral";
        
public const String DrawingFileOpenErrorUnsupportedVersion = @"DrawingFileOpenErrorUnsupportedVersion";
        
public const String DrawingFilesDirectoryFullName = @"DrawingFilesDirectoryFullName";
        
public const String DrawingGuid = @"DrawingGuid";
        
public const String DrawingHeight = @"DrawingHeight";
        
public const String DrawingOnDiskChangedMessage = @"DrawingOnDiskChangedMessage";
        
public const String DrawingSaveErrorUnSupportedAddons = @"DrawingSaveErrorUnSupportedAddons";
        
public const String DrawingSavingError = @"DrawingSavingError";
        
public const String DrawingSavingUnauthorizedAccessError = @"DrawingSavingUnauthorizedAccessError";
        
public const String DrawingsStoreBinMode = @"DrawingsStoreBinMode";
        
public const String DrawingsStoreXamlMode = @"DrawingsStoreXamlMode";
        
public const String DrawingWidth = @"DrawingWidth";
        
public const String DsChartItemDsBrush = @"DsChartItemDsBrush";
        
public const String DsChartItemHeaderInfo = @"DsChartItemHeaderInfo";
        
public const String DsChartItemValueInfo = @"DsChartItemValueInfo";
        
public const String DsCommandCommand = @"DsCommandCommand";
        
public const String DsCommandCommandUrl = @"DsCommandCommandUrl";
        
public const String DsCommandDsCommandOptions = @"DsCommandDsCommandOptions";
        
public const String DsCommandIsEnabledInfo = @"DsCommandIsEnabledInfo";
        
public const String DsConstantsCollectionDescription = @"DsConstantsCollectionDescription";
        
public const String DsPageBackground = @"DsPageBackground";
        
public const String DsPageBackgroundDescription = @"DsPageBackgroundDescription";
        
public const String DsPageDrawing = @"DsPageDrawing";
        
public const String DsPageDrawingForConstantValueConstantName = @"DsPageDrawingForConstantValueConstantName";
        
public const String DsPageDrawingForConstantValueConstantType = @"DsPageDrawingForConstantValueConstantType";
        
public const String DsPageDrawingForConstantValueFaceplateDsPageDrawingFileName = @"DsPageDrawingForConstantValueFaceplateDsPageDrawingFileName";
        
public const String DsPageDrawing_Desc = @"DsPageDrawing_Desc";
        
public const String DsPageDrawing_DescDescription = @"DsPageDrawing_DescDescription";
        
public const String DsPageDrawing_DsPageTypeGuid = @"DsPageDrawing_DsPageTypeGuid";
        
public const String DsPageDrawing_DsPageTypeObject = @"DsPageDrawing_DsPageTypeObject";
        
public const String DsPageDrawing_ExcludeFromTagSearch = @"DsPageDrawing_ExcludeFromTagSearch";
        
public const String DsPageDrawing_ExcludeFromTagSearchDescription = @"DsPageDrawing_ExcludeFromTagSearchDescription";
        
public const String DsPageDrawing_Group = @"DsPageDrawing_Group";
        
public const String DsPageDrawing_GroupDescription = @"DsPageDrawing_GroupDescription";
        
public const String DsPageDrawing_HorizontalAlignment = @"DsPageDrawing_HorizontalAlignment";
        
public const String DsPageDrawing_HorizontalAlignment_Description = @"DsPageDrawing_HorizontalAlignment_Description";
        
public const String DsPageDrawing_Name = @"DsPageDrawing_Name";
        
public const String DsPageDrawing_NameDescription = @"DsPageDrawing_NameDescription";
        
public const String DsPageDrawing_UnderlyingXaml = @"DsPageDrawing_UnderlyingXaml";
        
public const String DsPageDrawing_VerticalAlignment = @"DsPageDrawing_VerticalAlignment";
        
public const String DsPageDrawing_VerticalAlignment_Description = @"DsPageDrawing_VerticalAlignment_Description";
        
public const String DsPagesAndDsShapesDirectoryError = @"DsPagesAndDsShapesDirectoryError";
        
public const String DsPageStretchMode = @"DsPageStretchMode";
        
public const String DsPageStretchModeDescription = @"DsPageStretchModeDescription";
        
public const String DsPageTypeBase_Desc = @"DsPageTypeBase_Desc";
        
public const String DsPageTypeBase_IsFaceplate = @"DsPageTypeBase_IsFaceplate";
        
public const String DsPageTypeCategory = @"DsPageTypeCategory";
        
public const String DsProject = @"DsProject";
        
public const String DsProjectActuallyUsedAddons = @"DsProjectActuallyUsedAddons";
        
public const String DsProjectAddonsCollection = @"DsProjectAddonsCollection";
        
public const String DsProjectDesc = @"DsProjectDesc";
        
public const String DsProjectDrawingCurrentSerializationVersionDateTime = @"DsProjectDrawingCurrentSerializationVersionDateTime";
        
public const String DsProjectDrawingsStoreMode = @"DsProjectDrawingsStoreMode";
        
public const String DsProjectDsConstantsCollection = @"DsProjectDsConstantsCollection";
        
public const String DsProjectExeVersionDateTime = @"DsProjectExeVersionDateTime";
        
public const String DsProjectFileFullName = @"DsProjectFileFullName";
        
public const String DsProjectFileOpenErrorAddonIsNotFound = @"DsProjectFileOpenErrorAddonIsNotFound";
        
public const String DsProjectFileOpenErrorFileWasSavedInNewerVersion = @"DsProjectFileOpenErrorFileWasSavedInNewerVersion";
        
public const String DsProjectFileOpenErrorGeneral = @"DsProjectFileOpenErrorGeneral";
        
public const String DsProjectFileOpenWarningAddonIsNotFound = @"DsProjectFileOpenWarningAddonIsNotFound";
        
public const String DsProjectIsReadOnlyDueToLicense = @"DsProjectIsReadOnlyDueToLicense";
        
public const String DsProjectLoadedWithErrors = @"DsProjectLoadedWithErrors";
        
public const String DsProjectName = @"DsProjectName";
        
public const String DsProjectRootWindowProps = @"DsProjectRootWindowProps";
        
public const String DsProjectRootWindowPropsDescription = @"DsProjectRootWindowPropsDescription";
        
public const String DsProjectSavingError = @"DsProjectSavingError";
        
public const String DsProjectSavingUnauthorizedAccessError = @"DsProjectSavingUnauthorizedAccessError";
        
public const String DsProjectStartDsPageFileRelativePath = @"DsProjectStartDsPageFileRelativePath";
        
public const String DsProject_ConditionalDsCommandsCollection = @"DsProject_ConditionalDsCommandsCollection";
        
public const String DsProject_ConditionalDsCommandsCollection_Description = @"DsProject_ConditionalDsCommandsCollection_Description";
        
public const String DsProject_DataEngine = @"DsProject_DataEngine";
        
public const String DsProject_DataEngineGuidAndName = @"DsProject_DataEngineGuidAndName";
        
public const String DsProject_DefaultDsPageSize = @"DsProject_DefaultDsPageSize";
        
public const String DsProject_DefaultServerAddress = @"DsProject_DefaultServerAddress";
        
public const String DsProject_DsPageBackground = @"DsProject_DsPageBackground";
        
public const String DsProject_DsPageBackground_Description = @"DsProject_DsPageBackground_Description";
        
public const String DsProject_DsPageHorizontalAlignment = @"DsProject_DsPageHorizontalAlignment";
        
public const String DsProject_DsPageHorizontalAlignment_Description = @"DsProject_DsPageHorizontalAlignment_Description";
        
public const String DsProject_DsPageStretchMode = @"DsProject_DsPageStretchMode";
        
public const String DsProject_DsPageStretchMode_Description = @"DsProject_DsPageStretchMode_Description";
        
public const String DsProject_DsPageVerticalAlignment = @"DsProject_DsPageVerticalAlignment";
        
public const String DsProject_DsPageVerticalAlignment_Description = @"DsProject_DsPageVerticalAlignment_Description";
        
public const String DsProject_OperatorUICultureName = @"DsProject_OperatorUICultureName";
        
public const String DsProject_PlayWindowClassOptionsCollection = @"DsProject_PlayWindowClassOptionsCollection";
        
public const String DsProject_PlayWindowClassOptionsCollection_Description = @"DsProject_PlayWindowClassOptionsCollection_Description";
        
public const String DsProject_TryConvertXamlToDsShapes = @"DsProject_TryConvertXamlToDsShapes";
        
public const String DsShapeAngleDeltaInfo = @"DsShapeAngleDeltaInfo";
        
public const String DsShapeAngleFinal = @"DsShapeAngleFinal";
        
public const String DsShapeAngleInitial = @"DsShapeAngleInitial";
        
public const String DsShapeAngleInitialAdvanced = @"DsShapeAngleInitialAdvanced";
        
public const String DsShapeCenterDeltaPositionXInfo = @"DsShapeCenterDeltaPositionXInfo";
        
public const String DsShapeCenterDeltaPositionYInfo = @"DsShapeCenterDeltaPositionYInfo";
        
public const String DsShapeCenterFinalPosition = @"DsShapeCenterFinalPosition";
        
public const String DsShapeCenterInitialPosition = @"DsShapeCenterInitialPosition";
        
public const String DsShapeCenterInitialPositionAdvanced = @"DsShapeCenterInitialPositionAdvanced";
        
public const String DsShapeCenterPointMoved = @"DsShapeCenterPointMoved";
        
public const String DsShapeCenterRelativePosition = @"DsShapeCenterRelativePosition";
        
public const String DsShapeDesc = @"DsShapeDesc";
        
public const String DsShapeDrawing = @"DsShapeDrawing";
        
public const String DsShapeExportPropertiesSaveAsDialogTitle = @"DsShapeExportPropertiesSaveAsDialogTitle";
        
public const String DsShapeHeightDeltaInfo = @"DsShapeHeightDeltaInfo";
        
public const String DsShapeHeightFinal = @"DsShapeHeightFinal";
        
public const String DsShapeHeightInitial = @"DsShapeHeightInitial";
        
public const String DsShapeHeightInitialAdvanced = @"DsShapeHeightInitialAdvanced";
        
public const String DsShapeImportPropertiesDialogTitle = @"DsShapeImportPropertiesDialogTitle";
        
public const String DsShapeIsEnabledInfo = @"DsShapeIsEnabledInfo";
        
public const String DsShapeIsFlipped = @"DsShapeIsFlipped";
        
public const String DsShapeIsLocked = @"DsShapeIsLocked";
        
public const String DsShapeIsVisibleInfo = @"DsShapeIsVisibleInfo";
        
public const String DsShapeName = @"DsShapeName";
        
public const String DsShapeOpacityInfo = @"DsShapeOpacityInfo";
        
public const String DsShapeResetedCenterRelativePositionToOriginal = @"DsShapeResetedCenterRelativePositionToOriginal";
        
public const String DsShapeResetedSizeToOriginal = @"DsShapeResetedSizeToOriginal";
        
public const String DsShapes = @"DsShapes";
        
public const String DsShapeUpdated = @"DsShapeUpdated";
        
public const String DsShapeWidthDeltaInfo = @"DsShapeWidthDeltaInfo";
        
public const String DsShapeWidthFinal = @"DsShapeWidthFinal";
        
public const String DsShapeWidthInitial = @"DsShapeWidthInitial";
        
public const String DsShapeWidthInitialAdvanced = @"DsShapeWidthInitialAdvanced";
        
public const String DsShape_FieldOfView = @"DsShape_FieldOfView";
        
public const String DsShape_ResizeMode = @"DsShape_ResizeMode";
        
public const String DsShape_ResizeModeDescription = @"DsShape_ResizeModeDescription";
        
public const String DsShape_RotationX = @"DsShape_RotationX";
        
public const String DsShape_RotationY = @"DsShape_RotationY";
        
public const String DsShape_RotationZ = @"DsShape_RotationZ";
        
public const String DsTrendItemColor = @"DsTrendItemColor";
        
public const String DsTrendItemHdaId = @"DsTrendItemHdaId";
        
public const String DsTrendItemTag = @"DsTrendItemTag";
        
public const String DuplicateAddonsMessage = @"DuplicateAddonsMessage";
        
public const String EnableDisableBuzzer = @"EnableDisableBuzzer";
        
public const String ErrorMessageBoxCaption = @"ErrorMessageBoxCaption";
        
public const String ExportResultsButton = @"ExportResultsButton";
        
public const String ExportToCsvButtonText = @"ExportToCsvButtonText";
        
public const String ExportToXamlSaveAsDialogTitle = @"ExportToXamlSaveAsDialogTitle";
        
public const String FileExistsOverwriteQuestion = @"FileExistsOverwriteQuestion";
        
public const String FileMustBeInDsPagesDir = @"FileMustBeInDsPagesDir";
        
public const String FileMustBeInDsProjectDir = @"FileMustBeInDsProjectDir";
        
public const String FileMustBeInDsShapesDir = @"FileMustBeInDsShapesDir";
        
public const String FileNotFoundMessage = @"FileNotFoundMessage";
        
public const String FileOpenErrorFileNotFound = @"FileOpenErrorFileNotFound";
        
public const String FileOpenErrorFileVersionError = @"FileOpenErrorFileVersionError";
        
public const String FileOpenErrorMissingExtension = @"FileOpenErrorMissingExtension";
        
public const String FileUnknownExtensionMessage = @"FileUnknownExtensionMessage";
        
public const String FindButton = @"FindButton";
        
public const String FindButtonText = @"FindButtonText";
        
public const String FindDialogLabel = @"FindDialogLabel";
        
public const String FindNextButtonText = @"FindNextButtonText";
        
public const String FindReplaceBusyText = @"FindReplaceBusyText";
        
public const String FindReplaceDialogHint = @"FindReplaceDialogHint";
        
public const String FontSizeTextBoxToolTip = @"FontSizeTextBoxToolTip";
        
public const String FrameDrawingNotFoundErrorMessage = @"FrameDrawingNotFoundErrorMessage";
        
public const String FrameDsShape_FrameName = @"FrameDsShape_FrameName";
        
public const String FrameDsShape_FrameName_Description = @"FrameDsShape_FrameName_Description";
        
public const String FrameDsShape_StartDsPageFileRelativePath = @"FrameDsShape_StartDsPageFileRelativePath";
        
public const String FrameDsShape_StartDsPageFileRelativePath_Description = @"FrameDsShape_StartDsPageFileRelativePath_Description";
        
public const String GenericAddonTrendsInGroupCount = @"GenericAddonTrendsInGroupCount";
        
public const String GenericAddon_FileRelativePath = @"GenericAddon_FileRelativePath";
        
public const String GenericAddon_FileRelativePath_Description = @"GenericAddon_FileRelativePath_Description";
        
public const String GenericDataEngine_Description = @"GenericDataEngine_Description";
        
public const String GenericDataEngine_NameToDisplay = @"GenericDataEngine_NameToDisplay";
        
public const String GenericDsCommandOptionsParamsString = @"GenericDsCommandOptionsParamsString";
        
public const String GenericEmulationAddon_Desc = @"GenericEmulationAddon_Desc";
        
public const String GenericFaceplateDsPageType_Desc = @"GenericFaceplateDsPageType_Desc";
        
public const String GenericGraphicDsPageType_Desc = @"GenericGraphicDsPageType_Desc";
        
public const String GenericGraphicDsPageType_FramesDsPageFileRelativePath = @"GenericGraphicDsPageType_FramesDsPageFileRelativePath";
        
public const String GenericGraphicDsPageType_FramesDsPageFileRelativePath_Description = @"GenericGraphicDsPageType_FramesDsPageFileRelativePath_Description";
        
public const String Geometry3DCategory = @"Geometry3DCategory";
        
public const String GeometryAdvancedCategory = @"GeometryAdvancedCategory";
        
public const String GeometryCategory = @"GeometryCategory";
        
public const String GeometryDsShapeFillInfo = @"GeometryDsShapeFillInfo";
        
public const String GeometryDsShapeGeometryInfo = @"GeometryDsShapeGeometryInfo";
        
public const String GeometryDsShapeStrokeDashArray = @"GeometryDsShapeStrokeDashArray";
        
public const String GeometryDsShapeStrokeDashArrayDescription = @"GeometryDsShapeStrokeDashArrayDescription";
        
public const String GeometryDsShapeStrokeDashLength = @"GeometryDsShapeStrokeDashLength";
        
public const String GeometryDsShapeStrokeEndLineCap = @"GeometryDsShapeStrokeEndLineCap";
        
public const String GeometryDsShapeStrokeGapLength = @"GeometryDsShapeStrokeGapLength";
        
public const String GeometryDsShapeStrokeInfo = @"GeometryDsShapeStrokeInfo";
        
public const String GeometryDsShapeStrokeLineJoin = @"GeometryDsShapeStrokeLineJoin";
        
public const String GeometryDsShapeStrokeStartLineCap = @"GeometryDsShapeStrokeStartLineCap";
        
public const String GeometryDsShapeStrokeThickness = @"GeometryDsShapeStrokeThickness";
        
public const String GetDsPageDrawingsListDialogTitle = @"GetDsPageDrawingsListDialogTitle";
        
public const String GoLibraryButtonLabel = @"GoLibraryButtonLabel";
        
public const String GradientBrushTabItem = @"GradientBrushTabItem";
        
public const String HelpFileName = @"HelpFileName";
        
public const String ImportFromCsvButtonText = @"ImportFromCsvButtonText";
        
public const String ImportFromXamlDialogTitle = @"ImportFromXamlDialogTitle";
        
public const String InfoMessageBoxCaption = @"InfoMessageBoxCaption";
        
public const String InsertSpecialCharacterButtonToolTip = @"InsertSpecialCharacterButtonToolTip";
        
public const String InsertSpecialCharacterButtonToolTipDescription = @"InsertSpecialCharacterButtonToolTipDescription";
        
public const String JumpDsCommandOptions_FileRelativePath = @"JumpDsCommandOptions_FileRelativePath";
        
public const String LibPathLabel = @"LibPathLabel";
        
public const String LibraryDsPagesAndDsShapes = @"LibraryDsPagesAndDsShapes";
        
public const String MainBusyIndicatorText = @"MainBusyIndicatorText";
        
public const String MainCategory = @"MainCategory";
        
public const String MainGroup = @"MainGroup";
        
public const String MapDsShapeStrokeDashLength = @"MapDsShapeStrokeDashLength";
        
public const String MapDsShapeStrokeGapLength = @"MapDsShapeStrokeGapLength";
        
public const String MapDsShapeStrokeInfo = @"MapDsShapeStrokeInfo";
        
public const String MapDsShapeStrokeThickness = @"MapDsShapeStrokeThickness";
        
public const String MenuItemInfoDsCommand = @"MenuItemInfoDsCommand";
        
public const String MenuItemInfoHeaderInfo = @"MenuItemInfoHeaderInfo";
        
public const String MenuItemInfoIsVisibleInfo = @"MenuItemInfoIsVisibleInfo";
        
public const String MessageAreYouSureToClearAllQuestion = @"MessageAreYouSureToClearAllQuestion";
        
public const String MessageDeleteComplexDsShapesQuestion = @"MessageDeleteComplexDsShapesQuestion";
        
public const String MessageDeleteDsPagesQuestion = @"MessageDeleteDsPagesQuestion";
        
public const String MessageSaveFileQuestion = @"MessageSaveFileQuestion";
        
public const String MiddleControlPointSetAngleMenuItemHeader = @"MiddleControlPointSetAngleMenuItemHeader";
        
public const String MiddleControlPointSetHorizontalMenuItemHeader = @"MiddleControlPointSetHorizontalMenuItemHeader";
        
public const String MiddleControlPointSetVerticalMenuItemHeader = @"MiddleControlPointSetVerticalMenuItemHeader";
        
public const String MissingFile = @"MissingFile";
        
public const String ModelAndUIValueModelValue = @"ModelAndUIValueModelValue";
        
public const String ModelAndUIValueUIValue = @"ModelAndUIValueUIValue";
        
public const String ModelTagPropertyInfoAddToTrendGroups = @"ModelTagPropertyInfoAddToTrendGroups";
        
public const String ModelTagPropertyInfoEUInfo = @"ModelTagPropertyInfoEUInfo";
        
public const String ModelTagPropertyInfoFormatInfo = @"ModelTagPropertyInfoFormatInfo";
        
public const String ModelTagPropertyInfoHiAlarmInfo = @"ModelTagPropertyInfoHiAlarmInfo";
        
public const String ModelTagPropertyInfoHiHiAlarmInfo = @"ModelTagPropertyInfoHiHiAlarmInfo";
        
public const String ModelTagPropertyInfoLoAlarmInfo = @"ModelTagPropertyInfoLoAlarmInfo";
        
public const String ModelTagPropertyInfoLoLoAlarmInfo = @"ModelTagPropertyInfoLoLoAlarmInfo";
        
public const String ModelTagPropertyInfoMaxScaleInfo = @"ModelTagPropertyInfoMaxScaleInfo";
        
public const String ModelTagPropertyInfoMinScaleInfo = @"ModelTagPropertyInfoMinScaleInfo";
        
public const String ModelTagPropertyInfoPropertyPath = @"ModelTagPropertyInfoPropertyPath";
        
public const String ModelTagPropertyInfoPropertyPathToDisplay = @"ModelTagPropertyInfoPropertyPathToDisplay";
        
public const String ModelTagPropertyInfoTagType = @"ModelTagPropertyInfoTagType";
        
public const String ModelTagPropertyInfo_DescriptionInfo = @"ModelTagPropertyInfo_DescriptionInfo";
        
public const String MultiChartDsShape_AxisXBottomIsVisible = @"MultiChartDsShape_AxisXBottomIsVisible";
        
public const String MultiChartDsShape_AxisXTopIsVisible = @"MultiChartDsShape_AxisXTopIsVisible";
        
public const String MultiChartDsShape_AxisYLeftIsVisible = @"MultiChartDsShape_AxisYLeftIsVisible";
        
public const String MultiChartDsShape_AxisYRightIsVisible = @"MultiChartDsShape_AxisYRightIsVisible";
        
public const String MultiChartDsShape_ChartGridBrush = @"MultiChartDsShape_ChartGridBrush";
        
public const String MultiChartDsShape_ChartGridIsVisible = @"MultiChartDsShape_ChartGridIsVisible";
        
public const String MultiChartDsShape_ChartGridLabelsBottomIsVisible = @"MultiChartDsShape_ChartGridLabelsBottomIsVisible";
        
public const String MultiChartDsShape_ChartGridLabelsLeftIsVisible = @"MultiChartDsShape_ChartGridLabelsLeftIsVisible";
        
public const String MultiChartDsShape_ChartGridLabelsRightIsVisible = @"MultiChartDsShape_ChartGridLabelsRightIsVisible";
        
public const String MultiChartDsShape_ChartGridLabelsTopIsVisible = @"MultiChartDsShape_ChartGridLabelsTopIsVisible";
        
public const String MultiChartDsShape_EngUnitXInfo = @"MultiChartDsShape_EngUnitXInfo";
        
public const String MultiChartDsShape_EngUnitYInfo = @"MultiChartDsShape_EngUnitYInfo";
        
public const String MultiChartDsShape_FormatXInfo = @"MultiChartDsShape_FormatXInfo";
        
public const String MultiChartDsShape_FormatYInfo = @"MultiChartDsShape_FormatYInfo";
        
public const String MultiChartDsShape_MaximumXInfo = @"MultiChartDsShape_MaximumXInfo";
        
public const String MultiChartDsShape_MaximumYInfo = @"MultiChartDsShape_MaximumYInfo";
        
public const String MultiChartDsShape_MinimumXInfo = @"MultiChartDsShape_MinimumXInfo";
        
public const String MultiChartDsShape_MinimumYInfo = @"MultiChartDsShape_MinimumYInfo";
        
public const String MultiChartDsShape_MultiDsChartItemsCollection = @"MultiChartDsShape_MultiDsChartItemsCollection";
        
public const String MultiChartDsShape_TextTickFrequencyXInfo = @"MultiChartDsShape_TextTickFrequencyXInfo";
        
public const String MultiChartDsShape_TextTickFrequencyYInfo = @"MultiChartDsShape_TextTickFrequencyYInfo";
        
public const String MultiChartDsShape_TickFrequencyXInfo = @"MultiChartDsShape_TickFrequencyXInfo";
        
public const String MultiChartDsShape_TickFrequencyYInfo = @"MultiChartDsShape_TickFrequencyYInfo";
        
public const String MultiChartDsShape_TickLength = @"MultiChartDsShape_TickLength";
        
public const String MultiChartDsShape_TickStrokeThickness = @"MultiChartDsShape_TickStrokeThickness";
        
public const String MultiDsChartItem_AppearanceType = @"MultiDsChartItem_AppearanceType";
        
public const String MultiDsChartItem_FillDsBrush = @"MultiDsChartItem_FillDsBrush";
        
public const String MultiDsChartItem_FillIsVisible = @"MultiDsChartItem_FillIsVisible";
        
public const String MultiDsChartItem_LineDsBrush = @"MultiDsChartItem_LineDsBrush";
        
public const String MultiDsChartItem_LineIsVisible = @"MultiDsChartItem_LineIsVisible";
        
public const String MultiDsChartItem_LineStrokeDashArray = @"MultiDsChartItem_LineStrokeDashArray";
        
public const String MultiDsChartItem_LineStrokeDashArrayDescription = @"MultiDsChartItem_LineStrokeDashArrayDescription";
        
public const String MultiDsChartItem_LineStrokeDashLength = @"MultiDsChartItem_LineStrokeDashLength";
        
public const String MultiDsChartItem_LineStrokeGapLength = @"MultiDsChartItem_LineStrokeGapLength";
        
public const String MultiDsChartItem_LineStrokeThickness = @"MultiDsChartItem_LineStrokeThickness";
        
public const String MultiDsChartItem_PointDsBrush = @"MultiDsChartItem_PointDsBrush";
        
public const String MultiDsChartItem_PointGeometryInfo = @"MultiDsChartItem_PointGeometryInfo";
        
public const String MultiDsChartItem_PointNumberConstant = @"MultiDsChartItem_PointNumberConstant";
        
public const String MultiDsChartItem_PointNumberConstantDescription = @"MultiDsChartItem_PointNumberConstantDescription";
        
public const String MultiDsChartItem_PointNumberFormat = @"MultiDsChartItem_PointNumberFormat";
        
public const String MultiDsChartItem_PointsCountInfo = @"MultiDsChartItem_PointsCountInfo";
        
public const String MultiDsChartItem_PointsIsVisible = @"MultiDsChartItem_PointsIsVisible";
        
public const String MultiDsChartItem_PointsStartNumber = @"MultiDsChartItem_PointsStartNumber";
        
public const String MultiDsChartItem_PointStrokeThickness = @"MultiDsChartItem_PointStrokeThickness";
        
public const String MultiDsChartItem_PointValueXInfo = @"MultiDsChartItem_PointValueXInfo";
        
public const String MultiDsChartItem_PointValueYInfo = @"MultiDsChartItem_PointValueYInfo";
        
public const String MultiDsChartItem_TitleInfo = @"MultiDsChartItem_TitleInfo";
        
public const String MustDefineDataItemsMessage = @"MustDefineDataItemsMessage";
        
public const String NewDsPageDrawingDialogTitle = @"NewDsPageDrawingDialogTitle";
        
public const String NewDsShapeDrawingDialogTitle = @"NewDsShapeDrawingDialogTitle";
        
public const String NoConverter = @"NoConverter";
        
public const String NoDataMessage = @"NoDataMessage";
        
public const String NoSearchResults = @"NoSearchResults";
        
public const String NoSearchResultsToExport = @"NoSearchResultsToExport";
        
public const String NotAllComplexDsShapesRestoredMessage = @"NotAllComplexDsShapesRestoredMessage";
        
public const String NotAllComplexDsShapesUpdatedMessage = @"NotAllComplexDsShapesUpdatedMessage";
        
public const String NotAllDataWasReadMessage = @"NotAllDataWasReadMessage";
        
public const String NotDefined = @"NotDefined";
        
public const String NoTextToFind = @"NoTextToFind";
        
public const String OkButtonText = @"OkButtonText";
        
public const String OpenDsShapeDrawingFromComplexDsShape = @"OpenDsShapeDrawingFromComplexDsShape";
        
public const String OpenedUnsavedDrawingExistsMessage = @"OpenedUnsavedDrawingExistsMessage";
        
public const String Pages = @"Pages";
        
public const String PanoramaAddonAllowDesignModeInPlay = @"PanoramaAddonAllowDesignModeInPlay";
        
public const String PanoramaAddonAllowDesignModeInPlayDescription = @"PanoramaAddonAllowDesignModeInPlayDescription";
        
public const String PanoramaAddonAnimationDurationMs = @"PanoramaAddonAnimationDurationMs";
        
public const String PanoramaAddonDefaultCameraH = @"PanoramaAddonDefaultCameraH";
        
public const String PanoramaAddonDefaultCameraHDescription = @"PanoramaAddonDefaultCameraHDescription";
        
public const String PanoramaAddonFrameDsPageDrawingFileName = @"PanoramaAddonFrameDsPageDrawingFileName";
        
public const String PanoramaAddonFrameDsPageDrawingFileNameDescription = @"PanoramaAddonFrameDsPageDrawingFileNameDescription";
        
public const String PanoramaAddonShowLines = @"PanoramaAddonShowLines";
        
public const String PanoramaAddonShowLinesDescription = @"PanoramaAddonShowLinesDescription";
        
public const String PanoramaAddonTagsConstantsTypes = @"PanoramaAddonTagsConstantsTypes";
        
public const String PanoramaAddonTagsConstantsTypesDescription = @"PanoramaAddonTagsConstantsTypesDescription";
        
public const String PanoramaAddon_Desc = @"PanoramaAddon_Desc";
        
public const String PanoramaDsPageTypeCameraH = @"PanoramaDsPageTypeCameraH";
        
public const String PanoramaDsPageTypeCameraHDescription = @"PanoramaDsPageTypeCameraHDescription";
        
public const String PanoramaDsPageTypeDefaultViewAzimuth = @"PanoramaDsPageTypeDefaultViewAzimuth";
        
public const String PanoramaDsPageTypeFrameDsPageDrawingFileName = @"PanoramaDsPageTypeFrameDsPageDrawingFileName";
        
public const String PanoramaDsPageTypeFrameDsPageDrawingFileNameDescription = @"PanoramaDsPageTypeFrameDsPageDrawingFileNameDescription";
        
public const String PanoramaDsPageTypeHorizonAngle = @"PanoramaDsPageTypeHorizonAngle";
        
public const String PanoramaDsPageTypeHorizonAngleDescription = @"PanoramaDsPageTypeHorizonAngleDescription";
        
public const String PanoramaDsPageTypeHorizontalImageAngle = @"PanoramaDsPageTypeHorizontalImageAngle";
        
public const String PanoramaDsPageTypeLeftEdgeAzimuth = @"PanoramaDsPageTypeLeftEdgeAzimuth";
        
public const String PanoramaDsPageTypePanoramaType = @"PanoramaDsPageTypePanoramaType";
        
public const String PanoramaDsPageTypeX = @"PanoramaDsPageTypeX";
        
public const String PanoramaDsPageTypeY = @"PanoramaDsPageTypeY";
        
public const String PanoramaDsPageTypeZ = @"PanoramaDsPageTypeZ";
        
public const String PanoramaDsPageType_Desc = @"PanoramaDsPageType_Desc";
        
public const String PanoramaJumpDsCommandOptionsHorizontalDeltaToButton = @"PanoramaJumpDsCommandOptionsHorizontalDeltaToButton";
        
public const String PanoramaJumpDsCommandOptionsHorizontalDeltaToButtonDescription = @"PanoramaJumpDsCommandOptionsHorizontalDeltaToButtonDescription";
        
public const String PanoramaJumpDsCommandOptionsHorizontalLength = @"PanoramaJumpDsCommandOptionsHorizontalLength";
        
public const String PanoramaJumpDsCommandOptionsVerticalDelta = @"PanoramaJumpDsCommandOptionsVerticalDelta";
        
public const String PanoramaPlayDesignModeLabel = @"PanoramaPlayDesignModeLabel";
        
public const String PanoramaPlayDesignModeMessage = @"PanoramaPlayDesignModeMessage";
        
public const String ParamNumBrushTabItem = @"ParamNumBrushTabItem";
        
public const String ParamNumBrushTextBlock = @"ParamNumBrushTextBlock";
        
public const String Paste = @"Paste";
        
public const String PathControlPointAddMenuItemHeader = @"PathControlPointAddMenuItemHeader";
        
public const String PathControlPointDeleteMenuItemHeader = @"PathControlPointDeleteMenuItemHeader";
        
public const String PinButtonToolTip = @"PinButtonToolTip";
        
public const String PinButtonToolTipDescription = @"PinButtonToolTipDescription";
        
public const String PlayWindowClassInfo_WindowCategory = @"PlayWindowClassInfo_WindowCategory";
        
public const String PlayWindowClassInfo_WindowCategory_Description = @"PlayWindowClassInfo_WindowCategory_Description";
        
public const String PlayWindowClassOptions_CloseWindowsOnParentJump = @"PlayWindowClassOptions_CloseWindowsOnParentJump";
        
public const String PlayWindowClassOptions_CloseWindowsOnParentJump_Description = @"PlayWindowClassOptions_CloseWindowsOnParentJump_Description";
        
public const String PlayWindowClassOptions_PlayWindowClassInfo = @"PlayWindowClassOptions_PlayWindowClassInfo";
        
public const String PlayWindowClassOptions_PlayWindowClassInfo_Description = @"PlayWindowClassOptions_PlayWindowClassInfo_Description";
        
public const String PlayWindowClassOptions_WindowsMaxCount = @"PlayWindowClassOptions_WindowsMaxCount";
        
public const String PlayWindowClassOptions_WindowsMaxCount_Description = @"PlayWindowClassOptions_WindowsMaxCount_Description";
        
public const String PreviewCategory = @"PreviewCategory";
        
public const String ProgressInfo_AllDsPagesCacheUpdate_Description = @"ProgressInfo_AllDsPagesCacheUpdate_Description";
        
public const String ProgressInfo_AllDsPagesCacheUpdate_Header = @"ProgressInfo_AllDsPagesCacheUpdate_Header";
        
public const String ProgressInfo_DescriptionLine1_AddingDsShapes = @"ProgressInfo_DescriptionLine1_AddingDsShapes";
        
public const String ProgressInfo_DescriptionLine1_TryConvertUnderlyingContentXamlToDsShapes = @"ProgressInfo_DescriptionLine1_TryConvertUnderlyingContentXamlToDsShapes";
        
public const String ProgressInfo_GetAllDsPageDrawingInfos_Description = @"ProgressInfo_GetAllDsPageDrawingInfos_Description";
        
public const String ProgressInfo_ReadingCache_Description = @"ProgressInfo_ReadingCache_Description";
        
public const String ProgressInfo_SavingCache_Description = @"ProgressInfo_SavingCache_Description";
        
public const String Properties = @"Properties";
        
public const String PropertiesMenuItemHeader = @"PropertiesMenuItemHeader";
        
public const String PropertyGridHint = @"PropertyGridHint";
        
public const String PropsDeserializationError = @"PropsDeserializationError";
        
public const String PropsDeserializationErrorUnsupportedVersion = @"PropsDeserializationErrorUnsupportedVersion";
        
public const String PropsSerializationError = @"PropsSerializationError";
        
public const String PrototypeDsShapeDrawingCategory = @"PrototypeDsShapeDrawingCategory";
        
public const String QuestionMessageBoxCaption = @"QuestionMessageBoxCaption";
        
public const String ReadCsvFileError = @"ReadCsvFileError";
        
public const String ReadDrawingErrorMessage = @"ReadDrawingErrorMessage";
        
public const String ReadFrameDrawingErrorMessage = @"ReadFrameDrawingErrorMessage";
        
public const String ReadToolTipDrawingErrorMessage = @"ReadToolTipDrawingErrorMessage";
        
public const String RefreshAddonsCollectionButtonText = @"RefreshAddonsCollectionButtonText";
        
public const String ReplaceAll = @"ReplaceAll";
        
public const String ReplaceConfirmationQuestion = @"ReplaceConfirmationQuestion";
        
public const String ReplaceWith = @"ReplaceWith";
        
public const String RestoreDsProjectComplexDsShapesXamlModeError = @"RestoreDsProjectComplexDsShapesXamlModeError";
        
public const String RootPlayDsPageDrawingViewbox_MainFrame_ErrorMessage = @"RootPlayDsPageDrawingViewbox_MainFrame_ErrorMessage";
        
public const String SameTypeCloneableObjectsEditorControlHint = @"SameTypeCloneableObjectsEditorControlHint";
        
public const String SaveAsEmfFileButtonText = @"SaveAsEmfFileButtonText";
        
public const String SaveAsImageFileInputImageDimensions = @"SaveAsImageFileInputImageDimensions";
        
public const String SaveAsPngFileButtonText = @"SaveAsPngFileButtonText";
        
public const String SaveChangesQuestion = @"SaveChangesQuestion";
        
public const String SaveFilesToLatestSerializationVersionQuestion = @"SaveFilesToLatestSerializationVersionQuestion";
        
public const String SaveOriginalContentToFileButtonText = @"SaveOriginalContentToFileButtonText";
        
public const String SeeErrorLogForDetails = @"SeeErrorLogForDetails";
        
public const String SelectImageFromLibraryBusyText = @"SelectImageFromLibraryBusyText";
        
public const String SendKeyDsCommandOptionsKey = @"SendKeyDsCommandOptionsKey";
        
public const String SendKeyDsCommandOptionsKeyDescription = @"SendKeyDsCommandOptionsKeyDescription";
        
public const String SetAnglePrompt = @"SetAnglePrompt";
        
public const String SetAngleTitle = @"SetAngleTitle";
        
public const String SetInDsProjectProperties = @"SetInDsProjectProperties";
        
public const String SetTagsInfoMessage = @"SetTagsInfoMessage";
        
public const String ShowDsShapePropertiesButtonText = @"ShowDsShapePropertiesButtonText";
        
public const String ShowFaceplateForTagDsCommandOptions_FaceplateIndex = @"ShowFaceplateForTagDsCommandOptions_FaceplateIndex";
        
public const String ShowFaceplateForTagDsCommandOptions_FaceplateIndexDescription = @"ShowFaceplateForTagDsCommandOptions_FaceplateIndexDescription";
        
public const String ShowFaceplateForTagDsCommandOptions_Tag = @"ShowFaceplateForTagDsCommandOptions_Tag";
        
public const String ShowFaceplateForTagDsCommandOptions_TagDescription = @"ShowFaceplateForTagDsCommandOptions_TagDescription";
        
public const String ShowWindowDsCommandOptions_FileRelativePath = @"ShowWindowDsCommandOptions_FileRelativePath";
        
public const String ShowWindowDsCommandOptions_FrameName = @"ShowWindowDsCommandOptions_FrameName";
        
public const String ShowWindowDsCommandOptions_FrameName_Description = @"ShowWindowDsCommandOptions_FrameName_Description";
        
public const String ShowWindowDsCommandOptions_ParentWindow = @"ShowWindowDsCommandOptions_ParentWindow";
        
public const String ShowWindowDsCommandOptions_ShowOnTouchScreen = @"ShowWindowDsCommandOptions_ShowOnTouchScreen";
        
public const String ShowWindowDsCommandOptions_TitleInfo = @"ShowWindowDsCommandOptions_TitleInfo";
        
public const String ShowWindowDsCommandOptions_WindowCategory = @"ShowWindowDsCommandOptions_WindowCategory";
        
public const String ShowWindowDsCommandOptions_WindowCategoryMaxCount = @"ShowWindowDsCommandOptions_WindowCategoryMaxCount";
        
public const String ShowWindowDsCommandOptions_WindowCategory_Description = @"ShowWindowDsCommandOptions_WindowCategory_Description";
        
public const String ShowWindowDsCommandOptions_WindowFullScreen = @"ShowWindowDsCommandOptions_WindowFullScreen";
        
public const String ShowWindowDsCommandOptions_WindowResizeMode = @"ShowWindowDsCommandOptions_WindowResizeMode";
        
public const String ShowWindowDsCommandOptions_WindowShowInTaskbar = @"ShowWindowDsCommandOptions_WindowShowInTaskbar";
        
public const String ShowWindowDsCommandOptions_WindowStartupLocation = @"ShowWindowDsCommandOptions_WindowStartupLocation";
        
public const String ShowWindowDsCommandOptions_WindowStyle = @"ShowWindowDsCommandOptions_WindowStyle";
        
public const String ShowWindowDsCommandOptions_WindowTopmost = @"ShowWindowDsCommandOptions_WindowTopmost";
        
public const String SliderDsShapeInterval = @"SliderDsShapeInterval";
        
public const String SliderDsShapeLargeChangePercent = @"SliderDsShapeLargeChangePercent";
        
public const String SliderDsShapeMaximumInfo = @"SliderDsShapeMaximumInfo";
        
public const String SliderDsShapeMinimumInfo = @"SliderDsShapeMinimumInfo";
        
public const String SliderDsShapeSmallChangePercent = @"SliderDsShapeSmallChangePercent";
        
public const String SliderDsShapeValueInfo = @"SliderDsShapeValueInfo";
        
public const String SliderDsShapeXamlInfo = @"SliderDsShapeXamlInfo";
        
public const String SolidColorBrushTabItem = @"SolidColorBrushTabItem";
        
public const String SpecifyToolkitOperationOptionsMessage = @"SpecifyToolkitOperationOptionsMessage";
        
public const String StandardPagesAndDsShapesDirectoryError = @"StandardPagesAndDsShapesDirectoryError";
        
public const String StartProcessDsCommandOptionsArguments = @"StartProcessDsCommandOptionsArguments";
        
public const String StartProcessDsCommandOptionsCommand = @"StartProcessDsCommandOptionsCommand";
        
public const String StartProcessDsCommandOptionsCommandDescription = @"StartProcessDsCommandOptionsCommandDescription";
        
public const String StartToolkitOperationButtonText = @"StartToolkitOperationButtonText";
        
public const String StatmentValidationError = @"StatmentValidationError";
        
public const String StopButtonText = @"StopButtonText";
        
public const String StructConverterWindowIfExpression = @"StructConverterWindowIfExpression";
        
public const String SystemCategory = @"SystemCategory";
        
public const String TagInfoAreas = @"TagInfoAreas";
        
public const String TagInfo_DsPageFileRelativePath = @"TagInfo_DsPageFileRelativePath";
        
public const String TagInfo_TagName = @"TagInfo_TagName";
        
public const String TagInfo_TagType = @"TagInfo_TagType";
        
public const String TagAlarmsInfo_AlarmCategory0DsBrush = @"TagAlarmsInfo_AlarmCategory0DsBrush";
        
public const String TagAlarmsInfo_AlarmCategory1DsBrush = @"TagAlarmsInfo_AlarmCategory1DsBrush";
        
public const String TagAlarmsInfo_AlarmCategory2DsBrush = @"TagAlarmsInfo_AlarmCategory2DsBrush";
        
public const String TagAlarmsInfo_AlarmCategory3DsBrush = @"TagAlarmsInfo_AlarmCategory3DsBrush";
        
public const String TagAlarmsInfo_AlarmConditionInfosList = @"TagAlarmsInfo_AlarmConditionInfosList";
        
public const String TagAlarmsInfo_AlarmsIsVisible = @"TagAlarmsInfo_AlarmsIsVisible";
        
public const String TagAlarmsInfo_CsvDbFileName = @"TagAlarmsInfo_CsvDbFileName";
        
public const String TagAlarmsInfo_CsvDbFileName_Description = @"TagAlarmsInfo_CsvDbFileName_Description";
        
public const String TagTypeInfoConstant = @"TagTypeInfoConstant";
        
public const String TagTypeInfoDsPageFileRelativePaths = @"TagTypeInfoDsPageFileRelativePaths";
        
public const String TagTypeInfoPageFileRelativePaths = @"TagTypeInfoPageFileRelativePaths";
        
public const String TagTypeInfoTagType = @"TagTypeInfoTagType";
        
public const String TextBlockDsShapeBackgroundInfo = @"TextBlockDsShapeBackgroundInfo";
        
public const String TextBlockDsShapeForegroundInfo = @"TextBlockDsShapeForegroundInfo";
        
public const String TextBlockDsShapeVerticalAlignment = @"TextBlockDsShapeVerticalAlignment";
        
public const String TextBoxDsShapeIsReadOnlyInfo = @"TextBoxDsShapeIsReadOnlyInfo";
        
public const String TextDsShapeDsFont = @"TextDsShapeDsFont";
        
public const String TextDsShapeTextAlignment = @"TextDsShapeTextAlignment";
        
public const String TextDsShapeTextDecorations = @"TextDsShapeTextDecorations";
        
public const String TextDsShapeTextInfo = @"TextDsShapeTextInfo";
        
public const String TextDsShapeTextStretch = @"TextDsShapeTextStretch";
        
public const String TextDsShapeTextWrapping = @"TextDsShapeTextWrapping";
        
public const String TextToFindLabel = @"TextToFindLabel";
        
public const String ToggleButtonDsShapeCheckedContentInfo = @"ToggleButtonDsShapeCheckedContentInfo";
        
public const String ToggleButtonDsShapeIsCheckedInfo = @"ToggleButtonDsShapeIsCheckedInfo";
        
public const String ToggleButtonDsShapePressedContentInfo = @"ToggleButtonDsShapePressedContentInfo";
        
public const String ToggleButtonDsShapeUncheckedContentInfo = @"ToggleButtonDsShapeUncheckedContentInfo";
        
public const String ToolkitOperationError = @"ToolkitOperationError";
        
public const String ToolTipCategory = @"ToolTipCategory";
        
public const String ToolTipDsPageType_Desc = @"ToolTipDsPageType_Desc";
        
public const String TransparentSolidBrush = @"TransparentSolidBrush";
        
public const String TrendGroupDsShapeBackground = @"TrendGroupDsShapeBackground";
        
public const String TrendGroupDsShapeChartAxisBrush = @"TrendGroupDsShapeChartAxisBrush";
        
public const String TrendGroupDsShapeChartBackground = @"TrendGroupDsShapeChartBackground";
        
public const String TrendGroupDsShapeChartGridBrush = @"TrendGroupDsShapeChartGridBrush";
        
public const String TrendGroupDsShapeDsTrendItemsCollection = @"TrendGroupDsShapeDsTrendItemsCollection";
        
public const String TrendGroupDsShapeLabelsBrush = @"TrendGroupDsShapeLabelsBrush";
        
public const String TrendGroupDsShapeTrendsInfoTableVisibility = @"TrendGroupDsShapeTrendsInfoTableVisibility";
        
public const String TrendGroupDsShapeTrendsTuningVisibility = @"TrendGroupDsShapeTrendsTuningVisibility";
        
public const String UnauthorizedAcessMessage = @"UnauthorizedAcessMessage";
        
public const String UpdateComplexDsShapesToolkitOperationOptions = @"UpdateComplexDsShapesToolkitOperationOptions";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_ComplexDsShapeNames = @"UpdateComplexDsShapesToolkitOperationOptions_ComplexDsShapeNames";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_ComplexDsShapeNamesDescription = @"UpdateComplexDsShapesToolkitOperationOptions_ComplexDsShapeNamesDescription";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_MoveCenterPointOfDsShapes = @"UpdateComplexDsShapesToolkitOperationOptions_MoveCenterPointOfDsShapes";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_MoveCenterPointOfDsShapesDescription = @"UpdateComplexDsShapesToolkitOperationOptions_MoveCenterPointOfDsShapesDescription";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_ResetCenterRelativePositionToOriginal = @"UpdateComplexDsShapesToolkitOperationOptions_ResetCenterRelativePositionToOriginal";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_ResetCenterRelativePositionToOriginalDescription = @"UpdateComplexDsShapesToolkitOperationOptions_ResetCenterRelativePositionToOriginalDescription";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_ResetSizeToOriginal = @"UpdateComplexDsShapesToolkitOperationOptions_ResetSizeToOriginal";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_ResetSizeToOriginalDescription = @"UpdateComplexDsShapesToolkitOperationOptions_ResetSizeToOriginalDescription";
        
public const String UpdateComplexDsShapesToolkitOperationOptions_UpdateOnAllDsPages = @"UpdateComplexDsShapesToolkitOperationOptions_UpdateOnAllDsPages";
        
public const String UpdateDsPagesToolkitOperationOptionsTryUpdateDsPagesWithSizeOfImage = @"UpdateDsPagesToolkitOperationOptionsTryUpdateDsPagesWithSizeOfImage";
        
public const String UpdateDsPagesToolkitOperationOptionsTryUpdateDsPagesWithSizeOfImageDescription = @"UpdateDsPagesToolkitOperationOptionsTryUpdateDsPagesWithSizeOfImageDescription";
        
public const String UpdateObsoleteDrawingsQuestion = @"UpdateObsoleteDrawingsQuestion";
        
public const String ValueDataBindingBaseConverter = @"ValueDataBindingBaseConverter";
        
public const String ValueDataBindingBaseDataBindingItemsCollection = @"ValueDataBindingBaseDataBindingItemsCollection";
        
public const String ValueDataBindingBaseFormat = @"ValueDataBindingBaseFormat";
        
public const String WarningMessageBoxCaption = @"WarningMessageBoxCaption";
        
public const String WholeStringCheckBox = @"WholeStringCheckBox";
        
public const String WildcardsCheckBox = @"WildcardsCheckBox";
        
public const String WildcardsCheckBoxToolTip = @"WildcardsCheckBoxToolTip";
        
public const String WindowDsCommandOptionsBase_CurrentFrame = @"WindowDsCommandOptionsBase_CurrentFrame";
        
public const String WindowDsCommandOptionsBase_CurrentFrame_Description = @"WindowDsCommandOptionsBase_CurrentFrame_Description";
        
public const String WindowDsCommandOptionsBase_FrameName = @"WindowDsCommandOptionsBase_FrameName";
        
public const String WindowDsCommandOptionsBase_FrameName_Description = @"WindowDsCommandOptionsBase_FrameName_Description";
        
public const String WindowDsCommandOptionsBase_RootWindowNum = @"WindowDsCommandOptionsBase_RootWindowNum";
        
public const String WindowDsCommandOptionsBase_RootWindowNum_Description = @"WindowDsCommandOptionsBase_RootWindowNum_Description";
        
public const String WindowDsCommandOptionsBase_TargetWindow = @"WindowDsCommandOptionsBase_TargetWindow";
        
public const String WindowDsCommandOptionsBase_TargetWindow_Description = @"WindowDsCommandOptionsBase_TargetWindow_Description";
        
public const String WpfModel3DAddon_Desc = @"WpfModel3DAddon_Desc";
        
public const String WpfModel3DPlayWindowParamsAmbientLightColor = @"WpfModel3DPlayWindowParamsAmbientLightColor";
        
public const String WpfModel3DPlayWindowParamsBackgroundDsBrush = @"WpfModel3DPlayWindowParamsBackgroundDsBrush";
        
public const String WpfModel3DPlayWindowParamsTitleDsBrush = @"WpfModel3DPlayWindowParamsTitleDsBrush";
        
public const String XamlConverterWindowIfExpression = @"XamlConverterWindowIfExpression";
        
public const String XamlFileReadError = @"XamlFileReadError";
        
public const String XpsFileReadError = @"XpsFileReadError";
        
public const String ZoomboxAddon_Desc = @"ZoomboxAddon_Desc";
        
public const String ZoomboxBackButtonToolTip = @"ZoomboxBackButtonToolTip";
        
public const String ZoomboxDsPageType_Desc = @"ZoomboxDsPageType_Desc";
        
public const String ZoomboxForwardButtonToolTip = @"ZoomboxForwardButtonToolTip";
        
public const String ZoomboxHomeButtonToolTip = @"ZoomboxHomeButtonToolTip";
        
public const String TrendGroupDsShapeTrendsAxisXVisibility = @"TrendGroupDsShapeTrendsAxisXVisibility";
        
public const String TrendGroupDsShapeTrendsScrollbarsVisibility = @"TrendGroupDsShapeTrendsScrollbarsVisibility";
        
public const String TrendGroupDsShapeTrendsAxisYVisibility = @"TrendGroupDsShapeTrendsAxisYVisibility";
        
public const String DsProject_DefaultSystemNameToConnect = @"DsProject_DefaultSystemNameToConnect";
        
public const String VarComboBoxDsShape_MenuItemsInfo = @"VarComboBoxDsShape_MenuItemsInfo";
        
public const String ButtonDsShapeBase_RightClickDsCommand = @"ButtonDsShapeBase_RightClickDsCommand";
        
public const String ShowNavigationPanel = @"ShowNavigationPanel";
        
public const String ShowNavigationPanelDescription = @"ShowNavigationPanelDescription";
        
public const String DataEngineBase_ReverseElementIdsMapFileName = @"DataEngineBase_ReverseElementIdsMapFileName";
        
public const String DataEngineBase_ReverseElementIdsMapFileName_Description = @"DataEngineBase_ReverseElementIdsMapFileName_Description";
        
public const String ShowWindowDsCommandOptions_AutoCloseMs = @"ShowWindowDsCommandOptions_AutoCloseMs";
        
public const String ShowWindowDsCommandOptions_AutoCloseMs_Description = @"ShowWindowDsCommandOptions_AutoCloseMs_Description";
        
public const String GenericGraphicDsPageType_FrameInitializationInfosCollection = @"GenericGraphicDsPageType_FrameInitializationInfosCollection";
        
public const String ButtonDsShapeBase_MouseEnterDsCommand = @"ButtonDsShapeBase_MouseEnterDsCommand";
        
public const String ButtonDsShapeBase_MouseLeaveDsCommand = @"ButtonDsShapeBase_MouseLeaveDsCommand";
        
public const String ControlDsShapeToolTipPlacement = @"ControlDsShapeToolTipPlacement";
        
public const String ClassicTabStyleXaml = @"ClassicTabStyleXaml";
        
public const String DefaultTabStyleXaml = @"DefaultTabStyleXaml";
        
public const String TabItemInfo_PageFileRelativePath = @"TabItemInfo_PageFileRelativePath";
        
public const String TabDsShape_TabItemInfosCollection = @"TabDsShape_TabItemInfosCollection";
        
public const String DsTrendItem_ValueFormat = @"DsTrendItem_ValueFormat";
        
public const String MenuItemInfo_Path = @"MenuItemInfo_Path";
        
public const String TagAlarmsInfo_AlarmPriorityInfosList = @"TagAlarmsInfo_AlarmPriorityInfosList";
        
    } 
}