




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace Ssz.DataGrpc.ServerBase.Properties
{ 
    public class ResourceStrings
    {
        
        public const String OperationError_ProgressLabel = @"OperationError_ProgressLabel";
        
    } 
}