//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Operator.Design.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Operator.Design.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Pages and Shapes from Library.
        /// </summary>
        public static string AddDsPagesAndDsShapesFromLibraryMenu {
            get {
                return ResourceManager.GetString("AddDsPagesAndDsShapesFromLibraryMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Adds Pages and Shapes to Project from library.
        /// </summary>
        public static string AddDsPagesAndDsShapesFromLibraryToolTip {
            get {
                return ResourceManager.GetString("AddDsPagesAndDsShapesFromLibraryToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Shape.
        /// </summary>
        public static string AddDsShapeButtonText {
            get {
                return ResourceManager.GetString("AddDsShapeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addons Simple Shapes.
        /// </summary>
        public static string AddonSimpleDsShapesTreeViewItemHeader {
            get {
                return ResourceManager.GetString("AddonSimpleDsShapesTreeViewItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align bottom of all selected Shapes with bottom of the main selected Shape.
        /// </summary>
        public static string AlignBottomToolTip {
            get {
                return ResourceManager.GetString("AlignBottomToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align centers of all selected Shapes with center of the main selected Shape horizontally.
        /// </summary>
        public static string AlignHorizontalCentersToolTip {
            get {
                return ResourceManager.GetString("AlignHorizontalCentersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align left of all selected Shapes with left of the main selected Shape.
        /// </summary>
        public static string AlignLeftToolTip {
            get {
                return ResourceManager.GetString("AlignLeftToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        public static string AlignmentGroupHeader {
            get {
                return ResourceManager.GetString("AlignmentGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align right of all selected Shapes with right of the main selected Shape.
        /// </summary>
        public static string AlignRightToolTip {
            get {
                return ResourceManager.GetString("AlignRightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align top of all selected Shapes with top of the main selected Shape.
        /// </summary>
        public static string AlignTopToolTip {
            get {
                return ResourceManager.GetString("AlignTopToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Align centers of all selected Shapes with center of the main selected Shape vertically.
        /// </summary>
        public static string AlignVerticalCentersToolTip {
            get {
                return ResourceManager.GetString("AlignVerticalCentersToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please contact your regional Aftermarket Services for contract provision or renewal:
        ///Americas:
        ///    ots.support@Simcode.com
        ///Europe, Middle East and  Africa:
        ///    ots.support.emea@Simcode.com
        ///Asia Pacific:
        ///    Ssz.support.ap@Simcode.com.
        /// </summary>
        public static string AMSSupportInfo {
            get {
                return ResourceManager.GetString("AMSSupportInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string ApplicationMenuHeader {
            get {
                return ResourceManager.GetString("ApplicationMenuHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The toolkitOperation completed with error. See log file for details..
        /// </summary>
        public static string AppUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("AppUnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring Forward.
        /// </summary>
        public static string BringForward {
            get {
                return ResourceManager.GetString("BringForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bring to Front.
        /// </summary>
        public static string BringToFront {
            get {
                return ResourceManager.GetString("BringToFront", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sets drawing view scale to 100%..
        /// </summary>
        public static string Button100PercentToolTip {
            get {
                return ResourceManager.GetString("Button100PercentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows full drawing on screen.
        /// </summary>
        public static string ButtonFullDrawingToolTip {
            get {
                return ResourceManager.GetString("ButtonFullDrawingToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot copy files.
        /// </summary>
        public static string CannotCopyFiles {
            get {
                return ResourceManager.GetString("CannotCopyFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cann&apos;t edit standard complex Shape!.
        /// </summary>
        public static string CannotEditStandardComplexDsShapeMessage {
            get {
                return ResourceManager.GetString("CannotEditStandardComplexDsShapeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moves view to drawing center..
        /// </summary>
        public static string CenterToolTip {
            get {
                return ResourceManager.GetString("CenterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear List.
        /// </summary>
        public static string ClearRecentFilesListButtonLabel {
            get {
                return ResourceManager.GetString("ClearRecentFilesListButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Other.
        /// </summary>
        public static string CloseOtherDrawings {
            get {
                return ResourceManager.GetString("CloseOtherDrawings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compare Shapes content? Click &apos;Yes&apos; to compare complex Shapes content, click &apos;No&apos; to use only complex Shapes names for comparison..
        /// </summary>
        public static string CompareContentQuestion {
            get {
                return ResourceManager.GetString("CompareContentQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Properties.
        /// </summary>
        public static string ComplexDsShapeProperties {
            get {
                return ResourceManager.GetString("ComplexDsShapeProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Shapes.
        /// </summary>
        public static string ComplexDsShapesTreeViewItemHeader {
            get {
                return ResourceManager.GetString("ComplexDsShapesTreeViewItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert Content to Group.
        /// </summary>
        public static string ConvertToComplexDsShapeMenuItemHeader {
            get {
                return ResourceManager.GetString("ConvertToComplexDsShapeMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create Pages.
        /// </summary>
        public static string CreateDsPagesButtonLabel {
            get {
                return ResourceManager.GetString("CreateDsPagesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files for pages backgrounds (image, XPS, OXPS, XAML, HTML). New pages names will be the same as the names of the files (excluding extension). If page with that name already exists, new page will not be created..
        /// </summary>
        public static string CreateDsPagesSelectImageFilesMessageBox {
            get {
                return ResourceManager.GetString("CreateDsPagesSelectImageFilesMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates pages with backgrounds from selected set of files (image, XPS, XAML, HTML). New pages names will be the same as the names of the files (excluding extension). If page with that name already exists, new page will not be created..
        /// </summary>
        public static string CreateDsPagesToolTip {
            get {
                return ResourceManager.GetString("CreateDsPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crop Unused Space.
        /// </summary>
        public static string CropUnusedSpaceMenuItemHeader {
            get {
                return ResourceManager.GetString("CropUnusedSpaceMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        public static string DataGroupHeader {
            get {
                return ResourceManager.GetString("DataGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug Page.
        /// </summary>
        public static string DebugDsPageGroupHeader {
            get {
                return ResourceManager.GetString("DebugDsPageGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string DebugDsPagesGroupHeader {
            get {
                return ResourceManager.GetString("DebugDsPagesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Duplicate Tags.
        /// </summary>
        public static string DebugFindDuplicatesButtonLabel {
            get {
                return ResourceManager.GetString("DebugFindDuplicatesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds duplicate generic params values on pages.
        /// </summary>
        public static string DebugFindDuplicatesToolTip {
            get {
                return ResourceManager.GetString("DebugFindDuplicatesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Incorrect Pages Refs.
        /// </summary>
        public static string DebugFindIncorrectDsPagesRefsButtonLabel {
            get {
                return ResourceManager.GetString("DebugFindIncorrectDsPagesRefsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds jumps to non-existent pages and non-existent faceplates calls.
        /// </summary>
        public static string DebugFindIncorrectDsPagesRefsToolTip {
            get {
                return ResourceManager.GetString("DebugFindIncorrectDsPagesRefsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Incorrect Expressions.
        /// </summary>
        public static string DebugFindIncorrectExpressionsButtonLabel {
            get {
                return ResourceManager.GetString("DebugFindIncorrectExpressionsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds incorrect C# expressions in converters.
        /// </summary>
        public static string DebugFindIncorrectExpressionsToolTip {
            get {
                return ResourceManager.GetString("DebugFindIncorrectExpressionsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Incorrect OPC Tags.
        /// </summary>
        public static string DebugFindIncorrectOpcTagsButtonLabel {
            get {
                return ResourceManager.GetString("DebugFindIncorrectOpcTagsButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connects to model using default server URL (See Project -&gt; Properties) and finds incorrect OPC tags on pages.
        /// </summary>
        public static string DebugFindIncorrectOpcTagsToolTip {
            get {
                return ResourceManager.GetString("DebugFindIncorrectOpcTagsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Debug.
        /// </summary>
        public static string DebugRibbonTabHeader {
            get {
                return ResourceManager.GetString("DebugRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Shape(s).
        /// </summary>
        public static string DeleteComplexDsShapesText {
            get {
                return ResourceManager.GetString("DeleteComplexDsShapesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete drawing error..
        /// </summary>
        public static string DeleteDrawingError {
            get {
                return ResourceManager.GetString("DeleteDrawingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Page(s).
        /// </summary>
        public static string DeleteDsPagesText {
            get {
                return ResourceManager.GetString("DeleteDsPagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid Step.
        /// </summary>
        public static string DiscreteModeComboBoxToolTip {
            get {
                return ResourceManager.GetString("DiscreteModeComboBoxToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Turn On/Off discrete mode for Shapes sizes and positions.
        /// </summary>
        public static string DiscreteModeToolTip {
            get {
                return ResourceManager.GetString("DiscreteModeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute Horizontal.
        /// </summary>
        public static string DistributeHorizontalToolTip {
            get {
                return ResourceManager.GetString("DistributeHorizontalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Distribute Vertical.
        /// </summary>
        public static string DistributeVerticalToolTip {
            get {
                return ResourceManager.GetString("DistributeVerticalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string Done {
            get {
                return ResourceManager.GetString("Done", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing Explorer.
        /// </summary>
        public static string DrawingTabItemHeader {
            get {
                return ResourceManager.GetString("DrawingTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Properties.
        /// </summary>
        public static string DsPageProperties {
            get {
                return ResourceManager.GetString("DsPageProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages &amp; Shapes.
        /// </summary>
        public static string DsPagesAndDsShapesGroupHeader {
            get {
                return ResourceManager.GetString("DsPagesAndDsShapesGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string DsPagesTabItemHeader {
            get {
                return ResourceManager.GetString("DsPagesTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pages.
        /// </summary>
        public static string DsPagesToolkitGroupHeader {
            get {
                return ResourceManager.GetString("DsPagesToolkitGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page Style Properties.
        /// </summary>
        public static string DsPageTypeObjectProperties {
            get {
                return ResourceManager.GetString("DsPageTypeObjectProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot access Project directory for writing. Access is denied..
        /// </summary>
        public static string DsProjectDirectoryWriteAccessError {
            get {
                return ResourceManager.GetString("DsProjectDirectoryWriteAccessError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project File Not Found.
        /// </summary>
        public static string DsProjectFileNotFound {
            get {
                return ResourceManager.GetString("DsProjectFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were saved to disk.
        /// </summary>
        public static string DsProjectFileSavedToDiskMessageBox {
            get {
                return ResourceManager.GetString("DsProjectFileSavedToDiskMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string DsProjectGroupBoxHeader {
            get {
                return ResourceManager.GetString("DsProjectGroupBoxHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project is in read only mode! Project files cannot be saved! No further warnings will be generated! .
        /// </summary>
        public static string DsProjectIsReadOnlyMessage {
            get {
                return ResourceManager.GetString("DsProjectIsReadOnlyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string DsProjectPropertiesButtonText {
            get {
                return ResourceManager.GetString("DsProjectPropertiesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        public static string DsProjectRunButtonText {
            get {
                return ResourceManager.GetString("DsProjectRunButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Start Page.
        /// </summary>
        public static string DsProjectStartDsPageToolTip {
            get {
                return ResourceManager.GetString("DsProjectStartDsPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string DsProjectTreeViewItemHeader {
            get {
                return ResourceManager.GetString("DsProjectTreeViewItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Fill.
        /// </summary>
        public static string DsShapeDock {
            get {
                return ResourceManager.GetString("DsShapeDock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Bottom.
        /// </summary>
        public static string DsShapeDockBottom {
            get {
                return ResourceManager.GetString("DsShapeDockBottom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock.
        /// </summary>
        public static string DsShapeDockContextMenuGroup {
            get {
                return ResourceManager.GetString("DsShapeDockContextMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Left.
        /// </summary>
        public static string DsShapeDockLeft {
            get {
                return ResourceManager.GetString("DsShapeDockLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Right.
        /// </summary>
        public static string DsShapeDockRight {
            get {
                return ResourceManager.GetString("DsShapeDockRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dock Top.
        /// </summary>
        public static string DsShapeDockTop {
            get {
                return ResourceManager.GetString("DsShapeDockTop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export/Import Properties.
        /// </summary>
        public static string DsShapeExportImportProperties {
            get {
                return ResourceManager.GetString("DsShapeExportImportProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exports properties of selected Shape to XAML file..
        /// </summary>
        public static string DsShapeExportPropertiesDescription {
            get {
                return ResourceManager.GetString("DsShapeExportPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometry.
        /// </summary>
        public static string DsShapeGeometryGroupHeader {
            get {
                return ResourceManager.GetString("DsShapeGeometryGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape.
        /// </summary>
        public static string DsShapeGroupHeader {
            get {
                return ResourceManager.GetString("DsShapeGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Imports properties from XAML file into each of the selected Shapes..
        /// </summary>
        public static string DsShapeImportPropertiesDescription {
            get {
                return ResourceManager.GetString("DsShapeImportPropertiesDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string DsShapeLock {
            get {
                return ResourceManager.GetString("DsShapeLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lock.
        /// </summary>
        public static string DsShapeLockContextMenuGroup {
            get {
                return ResourceManager.GetString("DsShapeLockContextMenuGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order.
        /// </summary>
        public static string DsShapesOrder {
            get {
                return ResourceManager.GetString("DsShapesOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string DsShapesTabItemHeader {
            get {
                return ResourceManager.GetString("DsShapesTabItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes.
        /// </summary>
        public static string DsShapesToolkitGroupHeader {
            get {
                return ResourceManager.GetString("DsShapesToolkitGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unlock.
        /// </summary>
        public static string DsShapeUnlock {
            get {
                return ResourceManager.GetString("DsShapeUnlock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Geometry On/Off.
        /// </summary>
        public static string EditGeometry {
            get {
                return ResourceManager.GetString("EditGeometry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set height of all selected Shapes as height of the main selected Shape.
        /// </summary>
        public static string EqualizeHeightToolTip {
            get {
                return ResourceManager.GetString("EqualizeHeightToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set width of all selected Shapes as width of the main selected Shape.
        /// </summary>
        public static string EqualizeWidthToolTip {
            get {
                return ResourceManager.GetString("EqualizeWidthToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to XAML.
        /// </summary>
        public static string ExportToXamlButtonText {
            get {
                return ResourceManager.GetString("ExportToXamlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select one or more pages to export to XAML.
        /// </summary>
        public static string ExportToXamlGetDsPageDrawingInfosListFromUser {
            get {
                return ResourceManager.GetString("ExportToXamlGetDsPageDrawingInfosListFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Export to XAML.
        /// </summary>
        public static string ExportToXamlMenu {
            get {
                return ResourceManager.GetString("ExportToXamlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify new XAML file name to export to.
        /// </summary>
        public static string ExportToXamlSaveAsDialogTitle {
            get {
                return ResourceManager.GetString("ExportToXamlSaveAsDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export one or more pages from current Project to single XAML file..
        /// </summary>
        public static string ExportToXamlToolTip {
            get {
                return ResourceManager.GetString("ExportToXamlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File must be in Project \Shapes dir.
        /// </summary>
        public static string FileMustBeInDsShapesDir {
            get {
                return ResourceManager.GetString("FileMustBeInDsShapesDir", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File saved in newer version of designer!.
        /// </summary>
        public static string FileSavedInNewerVersionOfDesign {
            get {
                return ResourceManager.GetString("FileSavedInNewerVersionOfDesign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files alredy exists:.
        /// </summary>
        public static string FilesExists {
            get {
                return ResourceManager.GetString("FilesExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace.
        /// </summary>
        public static string FindAndReplaceWindowTitle {
            get {
                return ResourceManager.GetString("FindAndReplaceWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        public static string FindMenu {
            get {
                return ResourceManager.GetString("FindMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finds object in Project by name or property value.
        /// </summary>
        public static string FindToolTip {
            get {
                return ResourceManager.GetString("FindToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flipes Shape horizontal relative to Center Point.
        /// </summary>
        public static string FlipHorizontalToolTip {
            get {
                return ResourceManager.GetString("FlipHorizontalToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Property.
        /// </summary>
        public static string GroupDsPagesByGroupText {
            get {
                return ResourceManager.GetString("GroupDsPagesByGroupText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string GroupDsPagesByMarkText {
            get {
                return ResourceManager.GetString("GroupDsPagesByMarkText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style Property.
        /// </summary>
        public static string GroupDsPagesByStyleText {
            get {
                return ResourceManager.GetString("GroupDsPagesByStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group by:.
        /// </summary>
        public static string GroupDsPagesByText {
            get {
                return ResourceManager.GetString("GroupDsPagesByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grouping.
        /// </summary>
        public static string GroupingMenuItemHeader {
            get {
                return ResourceManager.GetString("GroupingMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string GroupMenuItemHeader {
            get {
                return ResourceManager.GetString("GroupMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show information about the application..
        /// </summary>
        public static string HelpToolTip {
            get {
                return ResourceManager.GetString("HelpToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from XAML.
        /// </summary>
        public static string ImportFromXamlButtonText {
            get {
                return ResourceManager.GetString("ImportFromXamlButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify XAML file name to import.
        /// </summary>
        public static string ImportFromXamlDialogTitle {
            get {
                return ResourceManager.GetString("ImportFromXamlDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Import from XAML.
        /// </summary>
        public static string ImportFromXamlMenu {
            get {
                return ResourceManager.GetString("ImportFromXamlMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import single XAML file with one or more pages into current Project..
        /// </summary>
        public static string ImportFromXamlToolTip {
            get {
                return ResourceManager.GetString("ImportFromXamlToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Shape name to add:.
        /// </summary>
        public static string InputDsShapeNameToAdd {
            get {
                return ResourceManager.GetString("InputDsShapeNameToAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new name for Page:.
        /// </summary>
        public static string InputNewDsPageDrawingName {
            get {
                return ResourceManager.GetString("InputNewDsPageDrawingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input new name for Complex Shape:.
        /// </summary>
        public static string InputNewDsShapeDrawingName {
            get {
                return ResourceManager.GetString("InputNewDsShapeDrawingName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MainRibbonButtonText {
            get {
                return ResourceManager.GetString("MainRibbonButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string MainRibbonTabHeader {
            get {
                return ResourceManager.GetString("MainRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page name error! File with the same name allready exists..
        /// </summary>
        public static string NameErrorDsPageDrawing {
            get {
                return ResourceManager.GetString("NameErrorDsPageDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex Shape name error! File with the same name allready exists..
        /// </summary>
        public static string NameErrorDsShapeDrawing {
            get {
                return ResourceManager.GetString("NameErrorDsShapeDrawing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Page.
        /// </summary>
        public static string NewDsPageButtonText {
            get {
                return ResourceManager.GetString("NewDsPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new Page and opens it in editor..
        /// </summary>
        public static string NewDsPageToolTip {
            get {
                return ResourceManager.GetString("NewDsPageToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        public static string NewDsProjectButtonText {
            get {
                return ResourceManager.GetString("NewDsProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot create Project directory!.
        /// </summary>
        public static string NewDsProjectCannotCreateDirectory {
            get {
                return ResourceManager.GetString("NewDsProjectCannotCreateDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project directory does not exsist! Please, specify existing directory and try again..
        /// </summary>
        public static string NewDsProjectDirectoryDoesNotExsist {
            get {
                return ResourceManager.GetString("NewDsProjectDirectoryDoesNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project directory already exsists! Please, specify different Project name and try again..
        /// </summary>
        public static string NewDsProjectDirectoryExsists {
            get {
                return ResourceManager.GetString("NewDsProjectDirectoryExsists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify new Project location, where Project folder will be created..
        /// </summary>
        public static string NewDsProjectFolderDialogDescription {
            get {
                return ResourceManager.GetString("NewDsProjectFolderDialogDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, specify new Project name. This name will be used as Project directory name..
        /// </summary>
        public static string NewDsProjectNameInputDialogPrompt {
            get {
                return ResourceManager.GetString("NewDsProjectNameInputDialogPrompt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Shape.
        /// </summary>
        public static string NewDsShapeButtonText {
            get {
                return ResourceManager.GetString("NewDsShapeButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creates new Complex Shape Drawing and opens it in editor..
        /// </summary>
        public static string NewDsShapeToolTip {
            get {
                return ResourceManager.GetString("NewDsShapeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _New Project.
        /// </summary>
        public static string NewMenu {
            get {
                return ResourceManager.GetString("NewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create a new Project..
        /// </summary>
        public static string NewToolTip {
            get {
                return ResourceManager.GetString("NewToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Ssz.Operator.Play licenses are available..
        /// </summary>
        public static string NoFVLicense {
            get {
                return ResourceManager.GetString("NoFVLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ssz.Operator.Play License Unavailable.
        /// </summary>
        public static string NoFVLicenseTitle {
            get {
                return ResourceManager.GetString("NoFVLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editing a Ssz.Operator.Play Project requires a Maintenance License but none are available.  Ssz.Operator.Play will operate in Read-Only mode and you will be unable to save.
        ///Do you want to continue?.
        /// </summary>
        public static string NoMaintLicense {
            get {
                return ResourceManager.GetString("NoMaintLicense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maintenance License Unavailable.
        /// </summary>
        public static string NoMaintLicenseTitle {
            get {
                return ResourceManager.GetString("NoMaintLicenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select &apos;OK&apos; to Exit.
        /// </summary>
        public static string OkToExit {
            get {
                return ResourceManager.GetString("OkToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Shape(s).
        /// </summary>
        public static string OpenComplexDsShapesText {
            get {
                return ResourceManager.GetString("OpenComplexDsShapesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Page(s).
        /// </summary>
        public static string OpenDsPagesText {
            get {
                return ResourceManager.GetString("OpenDsPagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string OpenDsProjectButtonText {
            get {
                return ResourceManager.GetString("OpenDsProjectButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File(s) Location.
        /// </summary>
        public static string OpenFilesLocationOfComplexDsShapesText {
            get {
                return ResourceManager.GetString("OpenFilesLocationOfComplexDsShapesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File(s) Location.
        /// </summary>
        public static string OpenFilesLocationOfDsPagesText {
            get {
                return ResourceManager.GetString("OpenFilesLocationOfDsPagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Open Project.
        /// </summary>
        public static string OpenMenu {
            get {
                return ResourceManager.GetString("OpenMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open an existing Project..
        /// </summary>
        public static string OpenToolTip {
            get {
                return ResourceManager.GetString("OpenToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Name.
        /// </summary>
        public static string OrderDsShapesByNameText {
            get {
                return ResourceManager.GetString("OrderDsShapesByNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order Shapes by:.
        /// </summary>
        public static string OrderDsShapesByText {
            get {
                return ResourceManager.GetString("OrderDsShapesByText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Type.
        /// </summary>
        public static string OrderDsShapesByTypeText {
            get {
                return ResourceManager.GetString("OrderDsShapesByTypeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shape Z Index.
        /// </summary>
        public static string OrderDsShapesByZIndexText {
            get {
                return ResourceManager.GetString("OrderDsShapesByZIndexText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints current opened drawing..
        /// </summary>
        public static string PrintToolTip {
            get {
                return ResourceManager.GetString("PrintToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating Project....
        /// </summary>
        public static string ProgressInfo_CreatingDsProject_Header {
            get {
                return ResourceManager.GetString("ProgressInfo_CreatingDsProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading Project....
        /// </summary>
        public static string ProgressInfo_LoadingDsProject_Header {
            get {
                return ResourceManager.GetString("ProgressInfo_LoadingDsProject_Header", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        public static string Properties {
            get {
                return ResourceManager.GetString("Properties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Project Properties.
        /// </summary>
        public static string PropertiesMenu {
            get {
                return ResourceManager.GetString("PropertiesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show properties of current Project..
        /// </summary>
        public static string PropertiesToolTip {
            get {
                return ResourceManager.GetString("PropertiesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot read drawing. See error log for details..
        /// </summary>
        public static string ReadDrawingErrorMessage {
            get {
                return ResourceManager.GetString("ReadDrawingErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recent Projects.
        /// </summary>
        public static string RecentDsProjects {
            get {
                return ResourceManager.GetString("RecentDsProjects", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeats the last action..
        /// </summary>
        public static string RedoToolTip {
            get {
                return ResourceManager.GetString("RedoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh List.
        /// </summary>
        public static string RefreshDsPagesButtonText {
            get {
                return ResourceManager.GetString("RefreshDsPagesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh List.
        /// </summary>
        public static string RefreshDsShapesButtonText {
            get {
                return ResourceManager.GetString("RefreshDsShapesButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename.
        /// </summary>
        public static string RenameComplexDsShapeText {
            get {
                return ResourceManager.GetString("RenameComplexDsShapeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename page error..
        /// </summary>
        public static string RenameDsPageError {
            get {
                return ResourceManager.GetString("RenameDsPageError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rename Page.
        /// </summary>
        public static string RenameDsPageText {
            get {
                return ResourceManager.GetString("RenameDsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        public static string ReplaceMenu {
            get {
                return ResourceManager.GetString("ReplaceMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replaces in properties values.
        /// </summary>
        public static string ReplaceToolTip {
            get {
                return ResourceManager.GetString("ReplaceToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear Mark.
        /// </summary>
        public static string ResetStatusText {
            get {
                return ResourceManager.GetString("ResetStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates Shape clockwise 90 degrees..
        /// </summary>
        public static string RotateClockwiseToolTip {
            get {
                return ResourceManager.GetString("RotateClockwiseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotates Shape counterclockwise 90 degrees..
        /// </summary>
        public static string RotateCounterClockwiseToolTip {
            get {
                return ResourceManager.GetString("RotateCounterClockwiseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs current opened page..
        /// </summary>
        public static string RunCurrentToolTip {
            get {
                return ResourceManager.GetString("RunCurrentToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Runs the Project..
        /// </summary>
        public static string RunToolTip {
            get {
                return ResourceManager.GetString("RunToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves all opened drawings..
        /// </summary>
        public static string SaveAllToolTip {
            get {
                return ResourceManager.GetString("SaveAllToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves copy of current opened drawing with different name and opens it in editor..
        /// </summary>
        public static string SaveAsToolTip {
            get {
                return ResourceManager.GetString("SaveAsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saves current opened drawing..
        /// </summary>
        public static string SaveToolTip {
            get {
                return ResourceManager.GetString("SaveToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scale.
        /// </summary>
        public static string Scale {
            get {
                return ResourceManager.GetString("Scale", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select All.
        /// </summary>
        public static string SelectAllMenuItemHeader {
            get {
                return ResourceManager.GetString("SelectAllMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Backward.
        /// </summary>
        public static string SendBackward {
            get {
                return ResourceManager.GetString("SendBackward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send to Back.
        /// </summary>
        public static string SendToBack {
            get {
                return ResourceManager.GetString("SendToBack", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set as Project Start Page.
        /// </summary>
        public static string SetAsDsProjectStartDsPageText {
            get {
                return ResourceManager.GetString("SetAsDsProjectStartDsPageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mark.
        /// </summary>
        public static string SetStatusText {
            get {
                return ResourceManager.GetString("SetStatusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show/Hide Shapes Info.
        /// </summary>
        public static string ShowHideDsShapesInfoButtonLabel {
            get {
                return ResourceManager.GetString("ShowHideDsShapesInfoButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shows/hides tooltips with generic params values for each complex Shape on page.
        /// </summary>
        public static string ShowHideDsShapesInfoButtonToolTip {
            get {
                return ResourceManager.GetString("ShowHideDsShapesInfoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to F:.
        /// </summary>
        public static string ShowHideDsShapesInfoFontSize {
            get {
                return ResourceManager.GetString("ShowHideDsShapesInfoFontSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes Info Font Size.
        /// </summary>
        public static string ShowHideDsShapesInfoFontSizeToolTip {
            get {
                return ResourceManager.GetString("ShowHideDsShapesInfoFontSizeToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O:.
        /// </summary>
        public static string ShowHideDsShapesInfoOpacity {
            get {
                return ResourceManager.GetString("ShowHideDsShapesInfoOpacity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapes Info Opacity.
        /// </summary>
        public static string ShowHideDsShapesInfoOpacityToolTip {
            get {
                return ResourceManager.GetString("ShowHideDsShapesInfoOpacityToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Shape not Found.
        /// </summary>
        public static string SimpleDsShapeNotFound {
            get {
                return ResourceManager.GetString("SimpleDsShapeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Simple Shapes.
        /// </summary>
        public static string SimpleDsShapesTreeViewItemHeader {
            get {
                return ResourceManager.GetString("SimpleDsShapesTreeViewItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify region (in drawing coordinates) for removing Shapes from it.
        /// </summary>
        public static string SpecifyRemoveDsShapesFromDsPagesToolkitOperationOptionsMessage {
            get {
                return ResourceManager.GetString("SpecifyRemoveDsShapesFromDsPagesToolkitOperationOptionsMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Incorrect Pages Refs.
        /// </summary>
        public static string String1DebugFindIncorrectDsPagesRefsToolTip {
            get {
                return ResourceManager.GetString("String1DebugFindIncorrectDsPagesRefsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync with Active Drawing.
        /// </summary>
        public static string SyncWithActiveDrawingButtonToolTip {
            get {
                return ResourceManager.GetString("SyncWithActiveDrawingButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toolkit.
        /// </summary>
        public static string ToolkitRibbonTabHeader {
            get {
                return ResourceManager.GetString("ToolkitRibbonTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main.
        /// </summary>
        public static string TreeViewMainGroupHeader {
            get {
                return ResourceManager.GetString("TreeViewMainGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncknown reason:.
        /// </summary>
        public static string UncknownReason {
            get {
                return ResourceManager.GetString("UncknownReason", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reverses the last action..
        /// </summary>
        public static string UndoToolTip {
            get {
                return ResourceManager.GetString("UndoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup and Subst Params.
        /// </summary>
        public static string UngroupAndReplaceConstantsMenuItemHeader {
            get {
                return ResourceManager.GetString("UngroupAndReplaceConstantsMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ungroup.
        /// </summary>
        public static string UngroupMenuItemHeader {
            get {
                return ResourceManager.GetString("UngroupMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon(s) unavailable.
        /// </summary>
        public static string UnSupportedAddons {
            get {
                return ResourceManager.GetString("UnSupportedAddons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please, select pages and/or Shapes drawings to update Shapes on them..
        /// </summary>
        public static string UpdateComplexDsShapes_GetDsPageDrawingInfosListFromUser {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapes_GetDsPageDrawingInfosListFromUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shapes +.
        /// </summary>
        public static string UpdateComplexDsShapesExtendedText {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapesExtendedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shapes with options: select pages to update, reset Shapes size on pages to original, move centers of Shapes..
        /// </summary>
        public static string UpdateComplexDsShapesExtendedToolTip {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapesExtendedToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shapes on Page(s).
        /// </summary>
        public static string UpdateComplexDsShapesOnDsPagesText {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapesOnDsPagesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shape(s) Size on Pages.
        /// </summary>
        public static string UpdateComplexDsShapesSizeText {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapesSizeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Shapes.
        /// </summary>
        public static string UpdateComplexDsShapesText {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Each page contains its own copies of the complex Shapes. Therefore, when you change complex Shape drawing (prototype drawing), changes you made will not automatically appear on each page. In order to start toolkitOperation of updating of all complex Shapes on all pages with latest changes from prototype drawings, you need to push this button..
        /// </summary>
        public static string UpdateComplexDsShapesToolTip {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update on Other Drawings.
        /// </summary>
        public static string UpdateComplexDsShapeText {
            get {
                return ResourceManager.GetString("UpdateComplexDsShapeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Pages.
        /// </summary>
        public static string UpdateDsPagesButtonLabel {
            get {
                return ResourceManager.GetString("UpdateDsPagesButtonLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select files for updating pages backgrounds (image, XPS, XAML, HTML). Updating pages names are the same as the names of the files (excluding extension). If page with that name does not exist, file is skipped..
        /// </summary>
        public static string UpdateDsPagesSelectImageFilesMessageBox {
            get {
                return ResourceManager.GetString("UpdateDsPagesSelectImageFilesMessageBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updates pages backgrounds with selected set of files (image, XPS, XAML, HTML). Updating pages names are the same as the names of the files (excluding extension). If page with that name does not exist, file is skipped..
        /// </summary>
        public static string UpdateDsPagesToolTip {
            get {
                return ResourceManager.GetString("UpdateDsPagesToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drawing View.
        /// </summary>
        public static string ViewGroupHeader {
            get {
                return ResourceManager.GetString("ViewGroupHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning: Project start page is undefined.
        /// </summary>
        public static string WarningDsProjectStartupWindowIsUndefined {
            get {
                return ResourceManager.GetString("WarningDsProjectStartupWindowIsUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read Only:.
        /// </summary>
        public static string WindowTitleIsReadOnly {
            get {
                return ResourceManager.GetString("WindowTitleIsReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;No current file&gt;.
        /// </summary>
        public static string WindowTitleNoCurrentFile {
            get {
                return ResourceManager.GetString("WindowTitleNoCurrentFile", resourceCulture);
            }
        }
    }
}
