//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Operator.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class OperatorUIResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal OperatorUIResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Operator.Core.Properties.OperatorUIResources", typeof(OperatorUIResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Find Path to Point.
        /// </summary>
        public static string FindPathButtonText {
            get {
                return ResourceManager.GetString("FindPathButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find path.
        /// </summary>
        public static string FindPathFailed {
            get {
                return ResourceManager.GetString("FindPathFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path found. See yellow frames around jump buttons.
        /// </summary>
        public static string FindPathSucceded {
            get {
                return ResourceManager.GetString("FindPathSucceded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You are already at destination.
        /// </summary>
        public static string FindPathSuccededYouInDestinationPoint {
            get {
                return ResourceManager.GetString("FindPathSuccededYouInDestinationPoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        public static string GenericTrendsInfoTableControl_ColorColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_ColorColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string GenericTrendsInfoTableControl_DescriptionColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_DescriptionColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eng Units.
        /// </summary>
        public static string GenericTrendsInfoTableControl_EUColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_EUColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Param.
        /// </summary>
        public static string GenericTrendsInfoTableControl_HdaIdToDisplayColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_HdaIdToDisplayColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max.
        /// </summary>
        public static string GenericTrendsInfoTableControl_MaxScaleColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_MaxScaleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min.
        /// </summary>
        public static string GenericTrendsInfoTableControl_MinScaleColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_MinScaleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        public static string GenericTrendsInfoTableControl_VisibleColumn {
            get {
                return ResourceManager.GetString("GenericTrendsInfoTableControl_VisibleColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Go to Point.
        /// </summary>
        public static string GoToDsPageButtonText {
            get {
                return ResourceManager.GetString("GoToDsPageButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Time Axis.
        /// </summary>
        public static string TrendGroupControlDecreaseTime {
            get {
                return ResourceManager.GetString("TrendGroupControlDecreaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reduce Data Axis.
        /// </summary>
        public static string TrendGroupControlDecreaseValue {
            get {
                return ResourceManager.GetString("TrendGroupControlDecreaseValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlarge Time Axis.
        /// </summary>
        public static string TrendGroupControlIncreaseTime {
            get {
                return ResourceManager.GetString("TrendGroupControlIncreaseTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlarge Data Axis.
        /// </summary>
        public static string TrendGroupControlIncreaseValue {
            get {
                return ResourceManager.GetString("TrendGroupControlIncreaseValue", resourceCulture);
            }
        }
    }
}
