//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Operator.Core.Play.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Operator.Core.Play.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The toolkitOperation completed with error. See log file for details..
        /// </summary>
        public static string AppUnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("AppUnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Connected {
            get {
                object obj = ResourceManager.GetObject("Connected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon ConnectedWithWarning {
            get {
                object obj = ResourceManager.GetObject("ConnectedWithWarning", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to.
        /// </summary>
        public static string DataAccessProviderConnected {
            get {
                return ResourceManager.GetString("DataAccessProviderConnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected, Model Error.
        /// </summary>
        public static string DataAccessProviderConnectedWithWarning {
            get {
                return ResourceManager.GetString("DataAccessProviderConnectedWithWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from.
        /// </summary>
        public static string DataAccessProviderDisconnected {
            get {
                return ResourceManager.GetString("DataAccessProviderDisconnected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design Mode Turn ON/OFF.
        /// </summary>
        public static string DesignModeTurnOnOffMenuItemHeader {
            get {
                return ResourceManager.GetString("DesignModeTurnOnOffMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Disconnected {
            get {
                object obj = ResourceManager.GetObject("Disconnected", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File not found.
        /// </summary>
        public static string FileNotFound {
            get {
                return ResourceManager.GetString("FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find.
        /// </summary>
        public static string FindMenuItemHeader {
            get {
                return ResourceManager.GetString("FindMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jump to Page.
        /// </summary>
        public static string JumpToDsPageMenuItemHeader {
            get {
                return ResourceManager.GetString("JumpToDsPageMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Play Window.
        /// </summary>
        public static string NewRootWindowMenuItemHeader {
            get {
                return ResourceManager.GetString("NewRootWindowMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project doesn&apos;t contain any dsPage to display!.
        /// </summary>
        public static string NoDsPageToDispalyMessage {
            get {
                return ResourceManager.GetString("NoDsPageToDispalyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click OK to Exit.
        /// </summary>
        public static string OkToExit {
            get {
                return ResourceManager.GetString("OkToExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project Folder.
        /// </summary>
        public static string OpenDsProjectFolderMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenDsProjectFolderMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Log Files Folder.
        /// </summary>
        public static string OpenLogFilesFolderMenuItemHeader {
            get {
                return ResourceManager.GetString("OpenLogFilesFolderMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Windows Positions.
        /// </summary>
        public static string SaveCurrentPlayWindowsConfigurationMenuItemHeader {
            get {
                return ResourceManager.GetString("SaveCurrentPlayWindowsConfigurationMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup Touchscreen.
        /// </summary>
        public static string SetupTouchScreenMenuItemHeader {
            get {
                return ResourceManager.GetString("SetupTouchScreenMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Debug Window.
        /// </summary>
        public static string ShowDebugWindowMenuItemHeader {
            get {
                return ResourceManager.GetString("ShowDebugWindowMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show Virtual Keyboard.
        /// </summary>
        public static string ShowVirtualKeyboardMenuItemHeader {
            get {
                return ResourceManager.GetString("ShowVirtualKeyboardMenuItemHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project startup dsPage isn&apos;t defined! Please, specify it in &quot;Project Properties -&gt; Start Page&quot;.
        /// </summary>
        public static string StartDsPageIsNotDefinedMessage {
            get {
                return ResourceManager.GetString("StartDsPageIsNotDefinedMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move this window to touchscreen and push this button, if you want to set whole monitor area as touchscreen..
        /// </summary>
        public static string TouchScreenFinderButton1Text {
            get {
                return ResourceManager.GetString("TouchScreenFinderButton1Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resize this window and push this button, if you want to set area of this window as touchscreen area (usefull in some situations with remote desktop connections)..
        /// </summary>
        public static string TouchScreenFinderButton2Text {
            get {
                return ResourceManager.GetString("TouchScreenFinderButton2Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Touchscreen Configuration.
        /// </summary>
        public static string TouchScreenFinderButton3Text {
            get {
                return ResourceManager.GetString("TouchScreenFinderButton3Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Touchscreen is not configured! Configure it first using &quot;Setup Touchscreen&quot; menu item..
        /// </summary>
        public static string TouchScreenIsNotConfiguredMessage {
            get {
                return ResourceManager.GetString("TouchScreenIsNotConfiguredMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mouse click (touch not available).
        /// </summary>
        public static string TouchScreenModeMouseClick {
            get {
                return ResourceManager.GetString("TouchScreenModeMouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Multi touch available.
        /// </summary>
        public static string TouchScreenModeMultiTouch {
            get {
                return ResourceManager.GetString("TouchScreenModeMultiTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only single touch available.
        /// </summary>
        public static string TouchScreenModeSingleTouch {
            get {
                return ResourceManager.GetString("TouchScreenModeSingleTouch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Virtual keyboard is not supported.
        /// </summary>
        public static string VirtualKeyboardNotSupportedMessage {
            get {
                return ResourceManager.GetString("VirtualKeyboardNotSupportedMessage", resourceCulture);
            }
        }
    }
}
