// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Ssz.Dcs.CentralServer.Common.EntityFramework;

#nullable disable

namespace Ssz.Dcs.CentralServer.Common.Migrations.SqliteMigrations
{
    [DbContext(typeof(SqliteDcsCentralServerDbContext))]
    partial class SqliteDcsCentralServerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.7");

            modelBuilder.Entity("OperatorSessionScenarioResult", b =>
                {
                    b.Property<long>("OperatorSessionsId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ScenarioResultsId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OperatorSessionsId", "ScenarioResultsId");

                    b.HasIndex("ScenarioResultsId");

                    b.ToTable("OperatorSessionScenarioResult");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.OpCompOperator", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("OpCompUserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("OpCompUserNameToDisplay")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OpCompUserWindowsUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long?>("OperatorId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorId");

                    b.ToTable("OpCompOperators");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.OperatorSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("File")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("OperatorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessModelingSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<byte>("Rating")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("Succeeded")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Task")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("OperatorUserId");

                    b.HasIndex("ProcessModelingSessionId");

                    b.ToTable("OperatorSessions");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModel", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Enterprise")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Plant")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessModelName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Unit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ProcessModels");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModelingSession", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("FinishDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<long>("InstructorUserId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ProcessModelId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<byte>("Type")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("InstructorUserId");

                    b.HasIndex("ProcessModelId");

                    b.ToTable("ProcessModelingSessions");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.Scenario", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialConditionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessModelId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ScenarioMaxProcessModelTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessModelId");

                    b.ToTable("Scenarios");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.ScenarioResult", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("FinishDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("FinishProcessModelTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InitialConditionName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("MaxPenalty")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Penalty")
                        .HasColumnType("INTEGER");

                    b.Property<long>("ProcessModelingSessionId")
                        .HasColumnType("INTEGER");

                    b.Property<ulong>("ScenarioMaxProcessModelTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ScenarioName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartDateTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("StartProcessModelTimeSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ProcessModelingSessionId");

                    b.ToTable("ScenarioResults");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.User", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("DomainUserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PersonnelNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProcessModelNames")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("OperatorSessionScenarioResult", b =>
                {
                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.OperatorSession", null)
                        .WithMany()
                        .HasForeignKey("OperatorSessionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.ScenarioResult", null)
                        .WithMany()
                        .HasForeignKey("ScenarioResultsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.OpCompOperator", b =>
                {
                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.User", "Operator")
                        .WithMany()
                        .HasForeignKey("OperatorId");

                    b.Navigation("Operator");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.OperatorSession", b =>
                {
                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.User", "OperatorUser")
                        .WithMany()
                        .HasForeignKey("OperatorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModelingSession", "ProcessModelingSession")
                        .WithMany()
                        .HasForeignKey("ProcessModelingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OperatorUser");

                    b.Navigation("ProcessModelingSession");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModelingSession", b =>
                {
                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.User", "InstructorUser")
                        .WithMany()
                        .HasForeignKey("InstructorUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModel", "ProcessModel")
                        .WithMany()
                        .HasForeignKey("ProcessModelId");

                    b.Navigation("InstructorUser");

                    b.Navigation("ProcessModel");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.Scenario", b =>
                {
                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModel", "ProcessModel")
                        .WithMany("Scenarios")
                        .HasForeignKey("ProcessModelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessModel");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.ScenarioResult", b =>
                {
                    b.HasOne("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModelingSession", "ProcessModelingSession")
                        .WithMany()
                        .HasForeignKey("ProcessModelingSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ProcessModelingSession");
                });

            modelBuilder.Entity("Ssz.Dcs.CentralServer.Common.EntityFramework.ProcessModel", b =>
                {
                    b.Navigation("Scenarios");
                });
#pragma warning restore 612, 618
        }
    }
}
