//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Utils.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Utils.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find or create addon config directory: {0}.
        /// </summary>
        internal static string AddonConfigDirectoryError {
            get {
                return ResourceManager.GetString("AddonConfigDirectoryError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Addon ConfigDirectory Error: Cannot contain subdirectory(-es): {0}.
        /// </summary>
        internal static string AddonConfigDirectoryError_CannotContainPath {
            get {
                return ResourceManager.GetString("AddonConfigDirectoryError_CannotContainPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddonNameIsEmpty.
        /// </summary>
        internal static string AddonNameIsEmpty {
            get {
                return ResourceManager.GetString("AddonNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available Addon is not found: {0}.
        /// </summary>
        internal static string AvailableAddonIsNotFound {
            get {
                return ResourceManager.GetString("AvailableAddonIsNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Calculation error.
        /// </summary>
        internal static string CalculationLambdaExpressionError {
            get {
                return ResourceManager.GetString("CalculationLambdaExpressionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File writing error.
        /// </summary>
        internal static string CsvDb_CsvFileWritingError {
            get {
                return ResourceManager.GetString("CsvDb_CsvFileWritingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File does not exist.
        /// </summary>
        internal static string CsvHelper_CsvFileDoesNotExist {
            get {
                return ResourceManager.GetString("CsvHelper_CsvFileDoesNotExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File contains duplicate key.
        /// </summary>
        internal static string CsvHelper_CsvFileDuplicateKey {
            get {
                return ResourceManager.GetString("CsvHelper_CsvFileDuplicateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File reading error.
        /// </summary>
        internal static string CsvHelper_CsvFileReadingError {
            get {
                return ResourceManager.GetString("CsvHelper_CsvFileReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired addon {0} failed..
        /// </summary>
        internal static string DesiredAddonFailed {
            get {
                return ResourceManager.GetString("DesiredAddonFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression error.
        /// </summary>
        internal static string PrepareLambdaExpressionError {
            get {
                return ResourceManager.GetString("PrepareLambdaExpressionError", resourceCulture);
            }
        }
    }
}
