




//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;

namespace Ssz.Dcs.CentralServer.Properties
{ 
    public class ResourceStrings
    {
        
        public const String DeleteUserError = @"DeleteUserError";
        
        public const String InsertUserError = @"InsertUserError";
        
        public const String LaunchedInstructorProgressLabel = @"LaunchedInstructorProgressLabel";
        
        public const String LaunchedOperatorProgressLabel = @"LaunchedOperatorProgressLabel";
        
        public const String LaunchingInstructorProgressErrorMessage = @"LaunchingInstructorProgressErrorMessage";
        
        public const String LaunchingInstructorProgressLabel = @"LaunchingInstructorProgressLabel";
        
        public const String LaunchingOperatorProgressErrorMessage = @"LaunchingOperatorProgressErrorMessage";
        
        public const String LaunchingOperatorProgressLabel = @"LaunchingOperatorProgressLabel";
        
        public const String OperationCompleted_ProgressLabel = @"OperationCompleted_ProgressLabel";
        
        public const String OperationError_ProgressLabel = @"OperationError_ProgressLabel";
        
        public const String OperatorDirectoryErrorProgressLabel = @"OperatorDirectoryErrorProgressLabel";
        
        public const String UpdateUserError = @"UpdateUserError";
        
    } 
}