//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Dcs.CentralServer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Dcs.CentralServer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Base module.
        /// </summary>
        public static string DcsCentralServerAddon_Desc {
            get {
                return ResourceManager.GetString("DcsCentralServerAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete user error.
        /// </summary>
        public static string DeleteUserError {
            get {
                return ResourceManager.GetString("DeleteUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server cannot read file.
        /// </summary>
        public static string FileReadingError {
            get {
                return ResourceManager.GetString("FileReadingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insert user error.
        /// </summary>
        public static string InsertUserError {
            get {
                return ResourceManager.GetString("InsertUserError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instructor files are downloaded.
        /// </summary>
        public static string LaunchedInstructorProgressLabel {
            get {
                return ResourceManager.GetString("LaunchedInstructorProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operator files are downloaded.
        /// </summary>
        public static string LaunchedOperatorProgressLabel {
            get {
                return ResourceManager.GetString("LaunchedOperatorProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching instructor failed.
        /// </summary>
        public static string LaunchingInstructorProgressErrorMessage {
            get {
                return ResourceManager.GetString("LaunchingInstructorProgressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading instructor files.
        /// </summary>
        public static string LaunchingInstructorProgressLabel {
            get {
                return ResourceManager.GetString("LaunchingInstructorProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Launching operator failed.
        /// </summary>
        public static string LaunchingOperatorProgressErrorMessage {
            get {
                return ResourceManager.GetString("LaunchingOperatorProgressErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Downloading operator files.
        /// </summary>
        public static string LaunchingOperatorProgressLabel {
            get {
                return ResourceManager.GetString("LaunchingOperatorProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Done.
        /// </summary>
        public static string OperationCompleted_ProgressLabel {
            get {
                return ResourceManager.GetString("OperationCompleted_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Error.
        /// </summary>
        public static string OperationError_ProgressLabel {
            get {
                return ResourceManager.GetString("OperationError_ProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot find operator interface files (*.dsProject).
        /// </summary>
        public static string OperatorDirectoryErrorProgressLabel {
            get {
                return ResourceManager.GetString("OperatorDirectoryErrorProgressLabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Interface:.
        /// </summary>
        public static string OperatorSessionDescription_InterfaceNameToDisplay {
            get {
                return ResourceManager.GetString("OperatorSessionDescription_InterfaceNameToDisplay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role:.
        /// </summary>
        public static string OperatorSessionDescription_OperatorRoleName {
            get {
                return ResourceManager.GetString("OperatorSessionDescription_OperatorRoleName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update user error..
        /// </summary>
        public static string UpdateUserError {
            get {
                return ResourceManager.GetString("UpdateUserError", resourceCulture);
            }
        }
    }
}
