//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Dcs.Addons.OpcClient.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Dcs.Addons.OpcClient.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context params.
        /// </summary>
        public static string ContextParams_Option {
            get {
                return ResourceManager.GetString("ContextParams_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC AE Server Host.
        /// </summary>
        public static string OpcAe_Host_Option {
            get {
                return ResourceManager.GetString("OpcAe_Host_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC AE Server ProgID.
        /// </summary>
        public static string OpcAe_ProgId_Option {
            get {
                return ResourceManager.GetString("OpcAe_ProgId_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC Client.
        /// </summary>
        public static string OpcClientAddon_Desc {
            get {
                return ResourceManager.GetString("OpcClientAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC DA Server Host.
        /// </summary>
        public static string OpcDa_Host_Option {
            get {
                return ResourceManager.GetString("OpcDa_Host_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC DA Server ProgID.
        /// </summary>
        public static string OpcDa_ProgId_Option {
            get {
                return ResourceManager.GetString("OpcDa_ProgId_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC HDA Server Host.
        /// </summary>
        public static string OpcHda_Host_Option {
            get {
                return ResourceManager.GetString("OpcHda_Host_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OPC HDA Server ProgID.
        /// </summary>
        public static string OpcHda_ProgId_Option {
            get {
                return ResourceManager.GetString("OpcHda_ProgId_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data access server address.
        /// </summary>
        public static string ServerAddress_Option {
            get {
                return ResourceManager.GetString("ServerAddress_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System name to connect.
        /// </summary>
        public static string SystemNameToConnect_Option {
            get {
                return ResourceManager.GetString("SystemNameToConnect_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System name to display to user.
        /// </summary>
        public static string SystemNameToConnect_ToDisplay_Option {
            get {
                return ResourceManager.GetString("SystemNameToConnect_ToDisplay_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USO OPC HDA Server Host.
        /// </summary>
        public static string UsoHda_Host_Option {
            get {
                return ResourceManager.GetString("UsoHda_Host_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USO OPC HDA Server ProgID.
        /// </summary>
        public static string UsoHda_ProgId_Option {
            get {
                return ResourceManager.GetString("UsoHda_ProgId_Option", resourceCulture);
            }
        }
    }
}
