<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <LangVersion>latest</LangVersion>	
    <AvaloniaUseCompiledBindingsByDefault>true</AvaloniaUseCompiledBindingsByDefault>
	  <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
	  <Platforms>AnyCPU</Platforms>
  </PropertyGroup>
 
  <ItemGroup>
    <AvaloniaResource Include="Assets\**" />
    <AvaloniaResource Include="Resources\Images\**" />
  </ItemGroup>
	
  <ItemGroup>
    <PackageReference Include="Avalonia" Version="12.1.1" />
    <PackageReference Include="Avalonia.Controls.DataGrid" Version="12.1.1" />
    <PackageReference Include="Avalonia.Markup.Xaml.Loader" Version="12.1.1" />
    <PackageReference Include="Avalonia.Themes.Fluent" Version="12.1.1" />
    <PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
    <!--Condition below is needed to remove Avalonia.Diagnostics package from build output in Release configuration.-->
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Egorozh.ColorPicker.Avalonia.Dialog" Version="11.0.3" />
	  <PackageReference Include="MessageBox.Avalonia" Version="12.0.0" />
	  <PackageReference Include="Oxyplot.Avalonia12" Version="2.1.2" />	  
	  <PackageReference Include="PanAndZoom" Version="12.0.0.1" />
	  <PackageReference Include="Svg.Controls.Avalonia" Version="12.0.0.13" />
	  <PackageReference Include="Svg.Controls.Skia.Avalonia" Version="12.0.0.13" />
    <PackageReference Include="OxyPlot.Core" Version="2.2.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\Ssz.DataAccessGrpc.Client\Ssz.DataAccessGrpc.Client.csproj" />
    <ProjectReference Include="..\..\Ssz.Utils.Avalonia\Ssz.Utils.Avalonia.csproj" />
    <ProjectReference Include="..\..\Ssz.Utils\Ssz.Utils.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\OperatorUIResources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>OperatorUIResources.resx</DependentUpon>
    </Compile>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\OperatorUIResources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>OperatorUIResources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>PublicResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>	
	
</Project>
