Logging: 
  LogLevel: 
    # задается уровень логирования событий в файлы журналов
    Default: "Debug"
Kestrel:   
  Endpoints: 
    HttpsDefaultCert: 
      Url: "https://*:60030"
ProgramDataDirectory: "C:\\CDT.PazCheck.Adapter_ProgramData"
---