Logging: 
  LogLevel: 
    # задается уровень логирования событий в файлы журналов
    Default: "Debug"
# путь до файла сертификата .pfx из которого используются закрытый и открытый ключи для шифрования и расшифровки секций конфигурационного файла, которые не должны храниться в открытом виде
ConfigurationCrypterCertificateFileName: "appsettings.pfx"
---