Logging:
  LogLevel:
    # задается уровень логирования событий в файлы журналов
    Default: "Warning"
    Grpc: "Warning"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Warning"
  SszLogger:
    # путь до директории где будут храниться файлы журналов событий
    LogsDirectory: "%ProgramData%\\Ssz\\Logs"
    # базовое имя файлов журналов
    LogFileName: "Dcs.CentralServer.log"
    # Флаг указывающий на необходимость дублирования события в стандартный поток вывода приложения
    DuplicateInConsole: "true"
    # количество дней которое должны храниться файлы журналов
    DaysCountToStoreFiles: "7"
    # максимальный размер одного файла журнала
    LogFileMaxSizeInBytes: "10000000"
    # размер всех файлов журналов при котором пользователям с ролью администратор дается предупреждение в виде сообщения которое появляется в веб-интерфейсе ИТ-решения
    LogFilesWarningSizeInBytes: "150000000"
    # максимальный размер всех фалов журналов. Если размер превышает этот предел самые старые лог-файлы автоматически удаляются      
    LogFilesMaxSizeInBytes: "200000000"
Kestrel:
  EndpointDefaults:
    Protocols: "Http1"
  Endpoints:
    HttpsDefaultCert:
      Url: "https://*:60060"
  Certificates:
    Default:
      # имя файла сертификата. Должен быть расположен в папке данных центрального сервера ПАЗ-Чек
      Path: "DefaultCertificate.pfx"
      # пароль от файла сертификата
      Password: "dyTLPB4EpLl5bcvsiGovWRhI6jJExKfm1zxwjOD+zwqQn7kW2HBPBkJALi7vD89g+1df3Srw8l+U69sPPwq2xenpefTTJ8GJY4lmzDwnc+o4Db3LkIoF0dyJ9F7zHm85P0HMCtibhBTVVfap6oCtfnOvKoPvYfaHnd4l5J9GM5q2Yk6jAniLMeh5gqclFZojq19qi3ghQGBwqCLA99tHsjZrMYsEmez49wBLhRDGlUAWZQbc9LOFtchsXJ6GW/+cYrMYPm9udId6+7xhczwnzDfPqBNyQ4AvzDCx1sghr1zocxPuDB63foa5eOAT8G+HSxntpyV/k5W7HleNCTQUBjGw6L1vedFmgXj10hPO70/SvfIN7Ybr2tS5ZU4NNsD4/i9pK7P9XWmUxxCwo6sskdY3jiCy3eM/oeNaLmSvamj0jdALSLY7vBqwni3Q4Wr5ksPccgdRZm+WIkbzgudtFE6U+VVUnyZiHX5uZwWuUxJhjNpqDJ3JJZCSWEKssZ+TGRfFojEmqEugYhmEKDwdXuIbXaXn9pgD0WyWeiuGNNxoirxg0URoHGqdD071gQRDyaAsQt3Joo1jqfqMQOMLvSXHe+UjtV/VYiWaJIDIJelbS45DGXKdalMgTavRjRR7I2Z4zxMlLm60q8pvVmFfnGTtSfkMA2AonrcXozbGbUk="
      AllowInvalid: "true"
DcsCentralServerAddonDesc: "Центральный сервер SSZ.DCS"
AllowedHosts: "*"
# задается язык сообщений в журналах событий которые доступны через веб интерфейс ИТ-решения возможные значения RU EN
UICulture: "RU"
ProgramDataDirectory: "C:\\CDT.CentralServer"
DataAccessClientUserName: ""
DataAccessClientPasswordHash: ""
DbType: "sqlite"
ConnectionStrings: 
  # MainDbConnection: "Host=localhost;Username=postgres;Password=postgres;Database=deltasim1;CommandTimeout=3600"  
# путь до файла сертификата .pfx из которого используются закрытый и открытый ключи для шифрования и расшифровки секций конфигурационного файла, которые не должны храниться в открытом виде
ConfigurationCrypterCertificateFileName: "appsettings.pfx"
ConfigurationCrypter: 
  adapterclient_password: ""
---
