Logging: 
  LogLevel: 
    # задается уровень логирования событий в файлы журналов
    Default: "Debug"
  SszLogger:
    # путь до директории где будут храниться файлы журналов событий
    LogsDirectory: "%ProgramData%\\Ssz\\Logs_Debug"
Kestrel:   
  Endpoints: 
    HttpsDefaultCert: 
      Url: "https://*:60030"
ProgramDataDirectory: "C:\\CDT.PazCheck.Adapter_ProgramData"
---