Logging:
  LogLevel:
    # задается уровень логирования событий в файлы журналов
    Default: "Warning"
    Grpc: "Warning"
    Microsoft: "Warning"
    Microsoft.Hosting.Lifetime: "Warning"
  SszLogger:
    # путь до директории где будут храниться файлы журналов событий
    LogsDirectory: "%ProgramData%\\Ssz\\Logs"
    # базовое имя файлов журналов
    LogFileName: "Dcs.CentralServer.log"
    # Флаг указывающий на необходимость дублирования события в стандартный поток вывода приложения
    DuplicateInConsole: "true"
    # количество дней которое должны храниться файлы журналов
    DaysCountToStoreFiles: "7"
    # максимальный размер одного файла журнала
    LogFileMaxSizeInBytes: "10000000"
    # размер всех файлов журналов при котором пользователям с ролью администратор дается предупреждение в виде сообщения которое появляется в веб-интерфейсе ИТ-решения
    LogFilesWarningSizeInBytes: "150000000"
    # максимальный размер всех фалов журналов. Если размер превышает этот предел самые старые лог-файлы автоматически удаляются      
    LogFilesMaxSizeInBytes: "200000000"
Kestrel:
  EndpointDefaults:
    Protocols: "Http1"
  Endpoints:
    HttpsDefaultCert:
      Url: "https://*:60060"
  Certificates:
    Default:
      # имя файла сертификата. Должен быть расположен в папке данных центрального сервера ПАЗ-Чек
      Path: "DefaultCertificate.pfx"
      # пароль от файла сертификата
      Password: "pLBr8qM/UTmUD0TTRv2zrMYRurkDONoMb73zNHAXBfBQI4F9EmTKt+QYaajfN/2vvNwsdRGnGVImtprKzK70aMPe2QFGivF3X3jH1j2dxvo8fJyxQBYjm5qAi8HZiHK5hDNsq0wjERAoKoDuHafd8dQ0JeSH0XKLZi1bCX1kpZxXNJ/doWPsgRe1PouZnATS6NHGGhwHtozAsS/pxTuUcpBq6/IqP+PkV4K+JtsDMZuHNqLpH0nyxMRoefDhSwTflCdbKyfSp0f+XDt14D1e0cX8SU1frowMB9VddSJpHsrCXPaG2z0Beja2V6ivqm8y0QtJ3j6r8IOr0rLZzmb20S/XizGFhtmIqZwQ0W/Z3Y+t/nP3BPmvKh0hDTrUC8BC7l05S+ryHnpJO1jTYhkJw3YFUx0zBoePUAyQxDuEoTEodJ+0ItjB7oeqoVdriWBngMLJatxZ469PSRp5mSp1tR9RVa14atLUfKy11yB2SwoSyGsafE2cbXXdLHWtUxBJdgXuOfyoj0hWG/NWTmlJB5q5gIIET5QhlK37TOIQ3AJOXfN0Ox6Je7apDCY1IPFxozUKX2cC8gKMPZw7EdH0FrQ02gnjYqdpOStg9razvEYHsQwuPHLYg3bKv0sKTpk1Q4jTAcBAQ6YWVJsLyHuR0QDUuGt7cS0hwBoUtTEDEj0="
      AllowInvalid: "true"
DcsCentralServerAddonDesc: "Центральный сервер SSZ.DCS"
AllowedHosts: "*"
# задается язык сообщений в журналах событий которые доступны через веб интерфейс ИТ-решения возможные значения RU EN
UICulture: "RU"
DataAccessClientUserName: ""
DataAccessClientPasswordHash: ""
# sqlite или postgres
DbType: "sqlite"
# ConnectionStrings:
#  MainDbConnection: "Host=localhost;Username=postgres;Password=postgres;Database=dcs;CommandTimeout=3600"
ConfigurationCrypter:
  adapterclient_password: ""
...
--- 
...
