Logging: 
  LogLevel: 
    # задается уровень логирования событий в файлы журналов
    Default: "Debug"
Kestrel:   
  Endpoints: 
    HttpsDefaultCert: 
      Url: "https://*:60060"
ProgramDataDirectory: "C:\\CDT.CentralServer"
---