Logging: 
  LogLevel: 
    # задается уровень логирования событий в файлы журналов
    Default: "Debug"
Kestrel:   
  Endpoints: 
    HttpsDefaultCert: 
      Url: "https://*:60070"
ProgramDataDirectory: "C:\\CDT.CentralServer(test)"
---