//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ssz.Dcs.Addons.ExperionEventsJournalFilesImporter.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ssz.Dcs.Addons.ExperionEventsJournalFilesImporter.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string CommonEventMessageFieldsToAdd_Option {
            get {
                return ResourceManager.GetString("CommonEventMessageFieldsToAdd_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Experion PKS events journal files importer.
        /// </summary>
        public static string ExperionEventsJournalFilesImporterAddon_Desc {
            get {
                return ResourceManager.GetString("ExperionEventsJournalFilesImporterAddon_Desc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string FileNameScope {
            get {
                return ResourceManager.GetString("FileNameScope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal files DateTime format.
        /// </summary>
        public static string JournalFiles_DateTimeFormat_Option {
            get {
                return ResourceManager.GetString("JournalFiles_DateTimeFormat_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal files path.
        /// </summary>
        public static string JournalFiles_Path_Option {
            get {
                return ResourceManager.GetString("JournalFiles_Path_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal files time zone.
        /// </summary>
        public static string JournalFiles_SourceTimeZone_Option {
            get {
                return ResourceManager.GetString("JournalFiles_SourceTimeZone_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal files type (RPT, CSV, HTM).
        /// </summary>
        public static string JournalFiles_Type_Option {
            get {
                return ResourceManager.GetString("JournalFiles_Type_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Journal Files delete scan period (seconds).
        /// </summary>
        public static string JournalFilesDeleteScanPeriodSeconds_Option {
            get {
                return ResourceManager.GetString("JournalFilesDeleteScanPeriodSeconds_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RPT journal files encoding.
        /// </summary>
        public static string RptFiles_Encoding_Option {
            get {
                return ResourceManager.GetString("RptFiles_Encoding_Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scan perion (seconds).
        /// </summary>
        public static string ScanPeriodSeconds_Option {
            get {
                return ResourceManager.GetString("ScanPeriodSeconds_Option", resourceCulture);
            }
        }
    }
}
